### ISSUE TITLE
[HLS] Missing Textures for Gonarch Decals

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Source-1-Games#1509]
When Gonarch lays baby headcrabs, or shoots that white stuff, the decals they leave on the ground do not show, and are black squares. I have set mat_compressedtextures to "1", and it still doesn't fix the problem.

![black birth](https://f.cloud.github.com/assets/5150898/1414218/276c4a14-3e72-11e3-84dc-5c820f8f9892.jpg)

![black cum](https://f.cloud.github.com/assets/5150898/1414222/3b4a82da-3e72-11e3-85b7-935c1ba13bc7.jpg)

![console](https://f.cloud.github.com/assets/5150898/1414223/522868b4-3e72-11e3-9747-08c0bbfdebe1.jpg)

Windows 7 64-bit
Radeon 4890

**Comment by shoober420** [comment]
I'm sure this was a fault on my end. Sorry about this.

**Comment by Yetoo1** [comment]
I am also experiencing this issue on Linux.

HL:S Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

System info here:
https://web.archive.org/web/20191207232514/https://pastebin.com/qJ5SPXg3

**Comment by Yetoo1** [comment]
@kisak-valve Can you reopen this since this issue still occurs or do you want a new issue report?

This also occurs in Windows 10, here's version & system info:
HL:S Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

https://web.archive.org/web/20201205100611/https://pastebin.com/kjyGA1wx
