### ISSUE TITLE
[TF2] Using -heapsize and -high in Startup Launch

### ISSUE THREAD

**Issue by APGRoboCop** [ValveSoftware/Source-1-Games#1543]
Hello I noticed when I play in TF2 with +developer 1 -high and -heapsize 1572864 or higher to use more heap and CPU on my newer PC with a AMD FM3+ 6-core and 16GB RAM. But the thing is when I looked at the TF2 Dev console the heap says 256mb and I'm not sure if I got the Startup launch options correct or not. Is this forced to use the safe recommended options to avoid TF2 getting any further crashes?

**Comment by uRandomAlex** [comment]
@Ruedii How can I raise max heapsize limit?
Sorry for being late.

**Comment by Ruedii** [comment]
The heapsize limit is set in the internal console variables, and can be set
with your autoexec.cfg file.

The large memory in modern systems has thrown the old rules out the
window.  The ideal maximum size is now based on map design and is generally
between 256MB and 720MB.

Because the game engine uses older memory handling techniques, setting the
heap size too big will result in cleanup pause lag.

@Ruedii <https://github.com/Ruedii> How can I raise max heapsize limit?
Sorry for being late.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ValveSoftware/Source-1-Games/issues/1543#issuecomment-232335795>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADBV6U2PHeC3FagKvDxKpMfyFkdW7GiYks5qVNUegaJpZM4BMMUN>
.

**Comment by Nephyrin** [comment]
`heapsize` is very misleading, as it is based on allocations for specific internal engine structures and has little to do with the total memory usage of the game.  Adjusting any of these values from their defaults is not recommended, and is unlikely to improve performance (and moderately likely to make it worse).
