### ISSUE TITLE
TF2 crashes while loading 2nd map on very high textures on OS X

### ISSUE THREAD

**Issue by LordHDL** [ValveSoftware/Source-1-Games#1829]
Setting the texture detail to very high on OS X will crash the game when a server switches maps or if you disconnect and join another server.  This may be related to issue https://github.com/ValveSoftware/Source-1-Games/issues/1828.

Here are a couple error dialogs I've gotten.

![screen shot 2014-09-23 at 7 25 06 pm](https://cloud.githubusercontent.com/assets/5182602/4383332/57388b12-439f-11e4-9995-569b0dc0845a.png)
![screen shot 2014-09-23 at 7 35 02 pm](https://cloud.githubusercontent.com/assets/5182602/4383333/57525c4a-439f-11e4-97a6-c995a04999bf.png)

**Comment by kisak-valve** [comment]
Hello @LordHDL, are you still experiencing this issue?

**Comment by hahagoni** [comment]
A progressive texture loading feature was added in the Tough Break update in order to resolve this specific issue. Not the best solution in my opinion, but it still should work.

-"Mac and Linux improvements (Windows Direct3D 9 players have these already)
Texture streaming now enabled
Reduced memory consumption by ~500 megs
Faster map loads!"
-"Players on Mac can now select 'High' texture settings"

Since then, I've not heard any report of this problem but I might be wrong.

**Comment by kisak-valve** [comment]
Thanks for the feedback @hahagoni, closing pending confirmation this is still an issue.
