### ISSUE TITLE
voice commands do not play

### ISSUE THREAD

**Issue by dmwit** [ValveSoftware/Source-1-Games#1880]
Since a recent update, all voiced sound effects have stopped playing. For example, the "Spy!" command plays no sound effect; I can't hear other players calling "Medic!"; the witty banter at the beginning of Helltower is sadly silent; etc. It makes for a much emptier-feeling game!

I have verified my game cache and checked all audio settings. Other sound effects (explosions, gunfire, footsteps, etc.) play normally. The console includes many copies of errors like this:

```
Failed to load sound "vo/soldier_Thanks01.mp3", file probably missing from disk/repository.
```

I don't see a file with that name on my disk. Then again, I don't see any mp3 files in `~/.local/share/Steam` at all, and sounds are still playing, so I must not be looking in the right place.

**Comment by dmwit** [comment]
Per discussion [on the forums](http://forums.tf2maps.net/showthread.php?t=21468), I also tried deleting all the sound caches in `~/.local/share/Steam/SteamApps/common/Team Fortress 2/tf`. These were all regenerated the next time I ran TF2, but there was no effect: the problem persists.

**Comment by Yttrium-tYcLief** [comment]
I believe "vo/soldier_Thanks01.mp3" refers to the file's path inside of the game's data archive, which could be extracted with a tool like GCFScape, which, of course, doesn't run on Linux.

This bug is most likely related to the [March 12, 2015](https://wiki.teamfortress.com/wiki/March_12,_2015_Patch) patch, which migrated voice sound bites to use mp3 instead of wav. The [March 18, 2015](https://wiki.teamfortress.com/wiki/March_18,_2015_Patch) patch updated the sound entries for files that weren't playing correctly.

My guess is that these sound entries are either broken on Linux or that your game install has something wrong with these entries. You might want to try a complete game reinstall just to make sure it's not an issue on your end.

**Comment by mastercoms** [comment]
Are you using SELinux?

**Comment by dmwit** [comment]
Aha! Thanks for the hint; that led me to https://github.com/ValveSoftware/steam-for-linux/issues/43, which suggests this workaround:

    setsebool -P allow_execheap 1

That workaround seems to do the trick for now; when I get a chance, I'll look into making a more targeted policy change for TF2.

In any case, this should probably be closed as a duplicate, if cross-project duplicates are possible in github's issue system. Thanks again!

**Comment by kisak-valve** [comment]
Closing as this appears to have been a system config issue.
