### ISSUE TITLE
You do not have this 3rd party mod installed?

### ISSUE THREAD

**Issue by jamiebatch452** [ValveSoftware/Source-1-Games#1892]
Hello there,

I am trying to connect to left 4 dead server I setup and it comes up saying "You do not have this 3rd party mod installed" ?? anyone know a fix?

**Comment by Theuaredead** [comment]
install third party map that the server is running
its not rocket science

**Comment by jamiebatch452** [comment]
I'm pretty sure your wrong, because it's a map that the server or game
comes with, it's not a custom map or even addon, but then again it is
rocket science to you.

On 4 June 2015 at 02:12, Theuaredead <notifications@github.com> wrote:

> install third party map that the server is running
> its not rocket science
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/Source-1-Games/issues/1892#issuecomment-108669069>
> .
>



--

**Comment by Theuaredead** [comment]
You're talking to someone who has been modding the Source Engine since 2010, and is making a full fledged L4D mod. Maps with no mission file load up the No Mercy Background and think they're loading the No Mercy campaign, meaning they get shuffled into the No Mercy Servers.

If you're missing an official map then you should verify your game cache.

If the map was different to your build the game would provide the error of "Your map differs from the Server's"

So go out and learn some social skills, because this isn't how you behave when you don't get the answer you want.


Plus Valve would of never helped you anyway since they've abandoned this GitHub

**Comment by kisak-valve** [comment]
Closing as this does not appear to be an actionable issue report. Left 4 Dead 2 servers with additional content from third party mods require the clients to have the corresponding mod installed.
