### ISSUE TITLE
[TF2] [Feature Request] [Casual Mode]: Ad-Hoc Connections (Joining Friends)

### ISSUE THREAD

**Issue by Contradicktory** [ValveSoftware/Source-1-Games#2022]
While Casual Mode has improved in leaps and bounds since its original implementation, it's still missing one key feature to make it a straight upgrade from Quickplay.

This feature is allowing ad-hoc connections, or joining friends.

Now, I should specify- **I am not suggesting returning MM servers to the server browser, or allowing direct-connects.** People should only be able to join a Matchmaking server through Matchmaking itself, or, through this system, by joining a friend's game when there is an available slot on the server.

**Comment by hahagoni** [comment]
I think using it as a backfill would improve player experience

**Comment by agrastiOs** [comment]
Certainly. I don't feel like there would be any disadvantages by adding the joining friends function back, unless Valve makes it so you play against players with similar skill. Of course, supposedly matchmaking looks a bit to the levels, but not much, I bet.

**Comment by Haze33E** [comment]
I think this feature needs to return as well but with a couple changes. I think the ad-hoc connections should be restricted to friends only. Previously it was anyone that visited your steam profile could join on you. I know streamers and youtubers hated this feature because of stream snipers and trolls. But this would also benefit normal players as well. I heard many stories of cheaters/hackers or trolls following people from one server to the next to make them rage quit the game.  
  
Another change I'd make is when you get sent a game invite from a friend who's in a party you join that party when joining the server. So you don't have to wait for your friends to return to the lobby when you want to party up with them. You would just join their game from their invite and be placed in their party.

**Comment by Wiiplay123** [comment]
But what about joining someone NOT on your friends list? That needs to be possible too.

**Comment by Contradicktory** [comment]
No it doesn't, it makes harassment and stalking easier.

**Comment by hahagoni** [comment]
@Wiiplay123 @Contradicktory It could work if it were implemented as an opt-in feature

**Comment by Wiiplay123** [comment]
Its already possible to join games with people you arent friends with,
except tf2 matchmaking messes it up.

**Comment by Wasmanr2** [comment]
With the JI update the new Party system allows players to join their friends. 
@kisak-valve you may close this.

**Comment by kisak-valve** [comment]
Thanks, closing.
