### ISSUE TITLE
[TF2] Vaccinator shows multiple types of damage resistance at once

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#2037]
I happened to catch a medic and patient who had all three damage resistance icons going at once.

![20161227154002_1](https://cloud.githubusercontent.com/assets/3085348/21508334/6076f53a-cc4e-11e6-8ee1-eac9ed420e48.jpg)

I mentioned this in the chat and someone else said it was just a visual glitch. What especially confuses me is that they're all lined up neatly like it was _designed_ to be able to handle multiple icons, instead of just having them all in the same spot clipping through each other. At any rate, it's a bug.

**Comment by Haze33E** [comment]
This isn't a "bug" the vaccinator is capable of having multiple resistances at once by deploying multiple ubers. If they stay there all the time then yes it's a bug but otherwise it's not. From the Gun Mettle Update - Vaccinator Uber deploys give the patient a 2.5 second bubble of 75% damage resistance of the current resist type and full crit resistance to that type. These bubbles do not disappear if the Medic stops targeting the current patient. Multiple bubbles of different types can be applied to the same patient or multiple patients given the same resist uber each consuming 1 charge.

**Comment by agrastiOs** [comment]
@kisak-valve This should be closed.

**Comment by kisak-valve** [comment]
Thanks, closing per the last couple comments.
