### ISSUE TITLE
Engine Error: Error in FL_Load_Glyph: glyph_index:752 ch:33f error:15

### ISSUE THREAD

**Issue by DirkyJerky** [ValveSoftware/Source-1-Games#2110]
When the character [0x033f](http://www.fileformat.info/info/unicode/char/033f/index.htm) is used in chat, it causes the above titled engine error and causes the game to terminate.

I don't know what `glyph_index` refers too,
`ch:33f` is the character referenced
`error:15` is the FreeType font engine error for "Invalid_Composite" (which makes sense for the character is a composite.

Curiously, the neighboring characters (in Unicode space) do not cause any issues, just the one.

I have a "friend" on a server I frequent that spams a complex emote in chat quite frequently, specifically 
"(ง ͡° ͜ʖ ͡°)=/̵͇̿̿/'̿'̿̿̿ ̿ ̿̿", which caused me to find this problem in the first place.

Im going to see what I can do to get the font files out of the vpks (and see if anything is wrong with them), if it is hopefully not a problem in my OS as a whole

OS: Kubuntu 16.10

**Comment by kisak-valve** [comment]
Hello @DirkyJerky, for clarity, which game are you encountering the issue with?

**Comment by DirkyJerky** [comment]
Oh sorry

Team Fortress 2

**Comment by DirkyJerky** [comment]
Also I might as well add, the issue only happens within the console, the chat messages all get relayed to console, which is triggering it.

**Comment by JeremieRapin** [comment]
Same on Fedora 25 and CS:Source

**Comment by rambo1462** [comment]
Same here in tf2 on ubuntu 16.10

**Comment by dmiller309** [comment]
I have the same problem as well. Once it starts happening, I can't get back into the match without it crashing again.

**Comment by sigsegv-mvm** [comment]
There are three callers to `FT_Load_Glyph` in `vguimatsurface.so`, and only one of them calls `Error` if the call fails: it's the call contained within the last/bottommost virtual member function of `class CLinuxFont`. I can't easily determine what the name/purpose of that function is, due to `CLinuxFont` being a class that's only present in Linux client builds, meaning that I possess no symbol information to directly use or correlate from.

Aside from taking actions such as changing the console font to one that has the particular glyphs that people are getting errors for, it might be a good idea to reevaluate whether that particular error situation is truly a fatal state that really ought to terminate the entire game; or if perhaps upon that failure some kind of fallback action could be taken that doesn't involve killing everything. Such as maybe loading the glyph from a fallback font, or displaying a box instead (or some other type of "broken character" symbol), or maybe just silently refusing to render that particular glyph.

**Comment by diamondburned** [comment]
I did some researches again and found out that both Ubuntu (OpenType font) and Noto Sans (TrueType font) have U+033F. If you really need it, I could extract `vguimatsurface.so` from Linux for you.

**Comment by transpetaflops** [comment]
A CVE was revealed in FreeType around the same time I started experiencing this problem. Upgrading to FreeType 2.7, where the vulnerability is fixed, resolved the problem for me.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10244

**Comment by kisak-valve** [comment]
Taking a look at Ubuntu, the fix has been shipped: https://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-10244.html

@DirkyJerky, are you still experiencing this issue with an up to date system?

Separately, are there any major distros that have not addressed this issue?

**Comment by DirkyJerky** [comment]
I just ran apt -- update & upgrade, did not seem to fix the problem. I may need to restart my computer and try again.

**Comment by kisak-valve** [comment]
I should have noted that TF2 did not crash on my Ubuntu 16.10 test box when using the test string with both the console and chat.

**Comment by diamondburned** [comment]
Don't think it's FreeType. Tried with TrueType and returned same thing. I found a fix though. Change console font to Unifont (fonts-unifont) and Chat font can be anything you want. I updated my reddit post. Here it is https://www.reddit.com/r/tf2/comments/64e2zo/solution_found_to_crash_bug_on_linux/

**Comment by DirkyJerky** [comment]
Yea changing the console font always worked; In `Verdana` font in other apps the character works just fine... My speculation is that source ships with a copy of the font and it is somehow corrupted that way. I could never find any relevant font files in any of the VPKs although.

**Comment by diamondburned** [comment]
All console don't worked with fonts-wqy-zenhei installed. However, it broke a lot of glyphs including lenny, so I went back to no fonts-wqy-zenhei.

**Comment by diamondburned** [comment]
Apologize. What I meant is that with fonts-wqy-zenhei installed, it no longer crashes with all fonts but break lenny.

**Comment by diamondburned** [comment]
**I FOUND THE PERMANENT SOLUTION!** This is really easy to do and I think it would only happen in custom HUDs. Anyway, first uninstall `fonts-wqy-zenhei`. Then, go to `chatscheme.res`. Afterwards, scroll down to the *Fonts* section then *Default*. Here you should see something like [this](http://i.imgur.com/3qSKv8q.png). Copy the 0x0*** (after 0x0000, in my case it's 0x017F). Go to Find and Replace, replace that value (0x017F here) with 0x036F. That should extend the Unicode character support a lot more. Fonts could be anything as long as it supports characters in the Combining Diacritical Marks section (Inherited in `charmap`).

**Comment by adduc** [comment]
I'm still crashing in Ubuntu 16.10.

I don't have a file named chatscheme.res on my system; how would I go about extracting it (from which VPK) to make the suggested change?

**Comment by diamondburned** [comment]
Hello, everyone. After a month of testing, the solution above didn't work. I'm very sorry. But, I found the solution (for realzies this time) and emailed John about this. Here's the email: https://pastebin.com/cFRQkjTU

[And here's the font file that I mentioned](https://mega.nz/#!MMEV0ZCL!T18S3idrgLxy9YReyhGF7GiBp9Ad804Ss7n6H7M_Etg)

**Comment by diamondburned** [comment]
After some more thinking I found out that this bug has something to do with Linux itself, although the Source (or Steam) team can fix it

- What Source/Steam needs to do: install `fonts-wqy-zenhei` or alternatives as the dependency
- What the font team needs to do: add support for characters such as U+033F to the font WenQuanYi Zen Hei

**Comment by diamondburned** [comment]
Bonus document: https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/

**Comment by catb0t** [comment]
I can't find any `chatscheme.res` in the `Team Fortress 2` folder, is it in one of the VPKs? I can't get the 32 bit VPK unpacker working right on x64, it seems to segfault.

**Comment by DirkyJerky** [comment]
I used wine and some popular named vpk tool to extract them.

**Comment by adduc** [comment]
Any update on this? I'm experiencing this in Ubuntu 17.04 daily. From sigsegv's findings, it appears this is not an issue with a missing font, but an error scenario handled in a non-ideal manner. I'd personally prefer seeing a square box or no character if it meant being able to continue to play instead of having to restart the client.

**Comment by sol8712** [comment]
Having this issue on Lubuntu 16.10 daily all up to date. It doesnt bug me(no pun) too much so ill just wait for them to fix it, or for somone to post some commands that i can just put in the terminal to fix it lol

**Comment by diamondburned** [comment]
`chatschemes.res` is from any HUD. This issue was mainly caused by the font WenQuanYi Zen Hei missing a few characters. You can either make your own file in `.config/fontconfig/fonts.conf` to do the same thing that `wqy-zenhei` does, but replace the font with Noto Sans, or install the package `wqy-zenhei`. 

What happens in TF2 is that it mistakens the character `033F` to be a Chinese character, thus using the font WenQuanYi Zen Hei to render it. However, the font itself doesn't have 033F, and the fontconfig system doesn't seem to bother using another font to render, so it just leaves the spaces blank.

**Comment by ElectricTriangle** [comment]
I can confirm that upgrading libfreetype6 to 2.8 fixes the crashes. In Debian (not sure about Ubuntu or other distros), this version isn't in stable yet so if you're using stable you'll have to download it from other sources such as your distro's package search tool.

**Comment by hauntingEcho** [comment]
I've been seeing the issue on Debian Stable as well.  I've just updated freetype from the testing repos, and will update if I continue seeing the issue.

**Comment by catb0t** [comment]
@ElectricTriangle in Ubuntu 18.04 `libfreetype6` is at least `2.8.1` so this seems to be mitigated from now on

**Comment by felipsmartins** [comment]
Debian 9, exactly the same issue. Sad!

**Comment by DirkyJerky** [comment]
I also confirm that updating `libfreetype6` to 2.8 OS-wide has fixed the issue for me.  I'll just close this thread now, for the bug seems to *possibly* have been non-source engine related.
