### ISSUE TITLE
[TF2] "An issue with your computer is blocking the VAC system" Transient error message

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#2150]
Since July 2016, I have been denied from joining any secure Team Fortress 2 game servers, at random intervals. This error is transient, and nothing I have tried so far has alleviated it. I have only seen this happen on Windows 7 Professional (x86_64), and it happens regardless of hardware or network connection. I have not encountered the bug at all on ~~OS X~~† or GNU/Linux The error also occurs on my secondary Steam account, on which I have purchased TF2.

Without success, I have tried the following solutions:
- Following the Execution Prevention instructions on the VAC help article
- Repairing the client service by using SteamClient with administrator permissions
- Clearing Windows event logs
- Restarting Steam and the Steam Service
- Verifying Team Fortress 2's game files
- Reinstalling Team Fortress 2 entirely
- Reinstalling Steam entirely
- Restarting the computer
- Using a different network router
- Using a different Ethernet NIC
- Using another Steam account

I have contacted Steam Support three times, and they finally informed me that I should clear Windows's application event logs. I have been doing so every time this error happens, and it does not help, even if the computer is reset. Typing "map itemtest" in my own developer console kicks me out of the listen server.

The only way I am able to launch Team Fortress 2 and play on any secure server-- including my own listen server with bots-- is to wait about an hour and then relaunch the game. After this, the error auto-magically fixes itself, and usually does not happen again for a few days. I am able to play any other VAC secured games in my library without issues; the issue is only experienced in Team Fortress 2.

†[5/7/2018] Found to be untrue, after restarting into macOS 10.13 in an attempt to avoid the issue.

**Comment by roboderpy** [comment]
After April 26 path it started to happen ~x4 times often

**Comment by BoctorPoo** [comment]
More findings on the issue:
- When VAC "breaks," the SteamService.exe process also uses one whole core of CPU continuously, causing degraded performance/battery.
- To join any secure games again, I must quit Steam, kill SteamService manually, then wait for up to 1 hour.
- Though the issue only originates from TF2, it can deny my connections to other VAC-secure games.
- The problem seems more likely to happen if the computer goes to sleep (Suspend) after a session of TF2.

As usual, none of this happens on Linux.

**Comment by Unmoving** [comment]
Happens to me know, after 10 years of playing TF2, the last couple on (Arch)Linux exclusively. So, it may happen on Linux 64bit :(

**Comment by BoctorPoo** [comment]
I thought this was stealth-patched in late 2017, but it now happens almost every day since March when I launch Team Fortress 2. As usual, accompanied by SteamClientService holding up an entire CPU core. I first hit the issue in Windows 10 Enterprise LTSB 1607, then restarted the computer and tried to play on macOS 10.13 (High Sierra), only for it to persist there.

SteamService seems picky about logging out of Steam on other PCs (with in-home sharing, I didn't expect that) and putting the system to sleep (suspension, not hibernation.) Other than required drivers, my OSes are always vanilla: I don't use software that hooks into any Steam or hl2-related processes. I'd be grateful to know exactly what I'm doing wrong, to keep this from happening.

**Comment by kisakvalve** [comment]
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by NULLYUKI** [comment]
Also the author has turned into a ghost, so this issue can be closed.

**Comment by kisak-valve** [comment]
Indeed. Closing because the reporting user has turned into a ghost.
