### ISSUE TITLE
[TF2] Casual and Competitive badges misplaced on 4:3 resolutions

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2168]
This is 1280x1024, 4:3
![20170222220330_1](https://cloud.githubusercontent.com/assets/15906773/23231861/fc57ede4-f951-11e6-8827-c658fc1efd48.jpg)
I can't click on the right-hand side of the medal, so that means the box for clicking is not misplaced, and the particles are also not misplaced.

**Comment by agrastiOs** [comment]
Closing due to this having been fixed as of the Jungle Inferno Update, thanks.

**Comment by CriticalFlaw** [comment]
This can be fixed in `resource/ui/pvprankpanel.res` by changing RankModel's tall value to something like 80, then change the fov to 55 so the badge doesn't look too tiny. This works on all resolutions. Just be sure to set the fov to 70 in if_mini, otherwise the badge will look too tiny on the match summary screen.

![Image](https://github.com/user-attachments/assets/d441e14a-eade-4947-b6a1-d13a201af473)
