### ISSUE TITLE
[HL2:DM] "Player model" list is empty

### ISSUE THREAD

**Issue by awedsa** [ValveSoftware/Source-1-Games#220]
The "Player model" list in Options>Multiplayer is empty.
The only way to change player models is using the "cl_playermodel" command.

![hl2dmbug](https://f.cloud.github.com/assets/3378854/267789/99e539b2-8ec7-11e2-8f8a-79469993937e.png)

As you can see there's another problem in the screenshot, the sprays logos are not shown.

System Information:
https://gist.github.com/awedsa/5180221

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.

**Comment by Adrianilloo** [comment]
This is not fixed, and still a basic annoying issue towards user experience. As someone explained in the past, this has to do with some command parsing change in the engine, making it to stop at the slash (`/`) and thus affecting `cl_playermodel` inputs, causing the game code to read and associate `models/` to the combine team, and setting a combine model as a fallback.

**Comment by kisak-valve** [comment]
Hello @Adrianilloo, you're most likely looking for #263 instead of this issue report.

**Comment by Sub-Zero1324** [comment]
@kisak-valve @bdeen-valve The player model selection is still broken as well as the sprays only make a sound but do not spray any image. I spoke to Tony Sergi who is no longer at Valve and he said the issue with the player model selection and the sprays not working is because the player models and sprays cannot be found as there is a bug in the GameUI.dll. This issue still exists in Half-Life 2 Deathmatch and any Half-Life 2 Deathmatch mod using the 2013 SDK. Also this is on the Windows and Linux side
