### ISSUE TITLE
Team Fortress 2 freezes while trying to load world

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Source-1-Games#2207]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/4904.
@furycd001 posted on 2017-03-20T08:02:46:

HI Guys

TF2 on my laptop has stopped working as of the most recent update. The game loads fine (maybe a bit slower than before) and I can access and play with all the menus. The problem is whenever I try to launch a game mode either online or offline it freezes while trying to load the world. How can I fix my TF2 install and start playing the game again :? My specs are listed below. Many thanks in advanced for your help and time...

**OS:** Ubuntu 16.04
**GRAPHICS:** NVIDIA C79 GeForce 9400M G / http://i.imgur.com/jRPz0y8.png
**CPU:** Intel Core2 Duo CPU P7350 @ 1.995GHz
**GPU:** Gallium 0.4 on NVAC - RAM: 631MiB / 1744MiB
**STEAM CLIENT:** Newest release with all updates installed.

STEAM + TF2 RUN FROM TERMINAL PRODUCES THIS http://paste.ubuntu.com/24210348/

**Comment by kisak-valve** [comment]
Hello @furycd001, I'm not able to reproduce this issue on my Gentoo Core 2 duo 2GHz / 2GB ram / NVS 320m (about the same as a 8600GTm) laptop. We'll need to see if others are having similar difficulties and see if we can find a pattern.

This game is using more ram and vram than your specs, so swap is needed to make up the difference, which can cause severe delays while waiting on the hard drive. Lowering your video settings may take some vram pressure off the system.

**Comment by furycd001** [comment]
Ok thank you for taking the time to check. I will try turning down my video settings next time I'm on my laptop. Strange how the game worked before and just stopped all of a sudden. My laptop is 8 years old and I do plan on buying a new one at the end of this year. Any recommendations for being able to play TF2 on a laptop a £600 budget

**Comment by Wasmanr2** [comment]
Tf2 for Linux does run on Opengl on default right ?
Also there is a chance that you might use a custom config to run tf2 better (i can provide you one if you want) and what kisak said "just lower your graphics".
Btw..never try to play games on a laptop. 
Especially not tf2. 
Build or buy a PC.

**Comment by furycd001** [comment]
I'm not sure because I have never checked. Before it always just ran for me and I never had any problems. I know I probably should build a gaming pc, but I've never got around to it lol. Yea I'm going to try lowering the graphics tonight and see if that makes any difference. How do I use / run a custom config file :? Cos I will happily try using one if you can link me to one. Many thanks in advanced for your time and help :-)

**Comment by Wasmanr2** [comment]
No problem. The best config for linux ubuntu etc. may be Felik's config, since it includes severall optimizations for linux too and mac.

And its quite easy to run the config.

The direct downloadlink for the config is this one 
 
https://gitlab.com/felik/TF2-Config/repository/archive.zip?ref=master

The only configs that you need are autoexec.cfg and nvidia.cfg.

The config need to put in here " Steam\steamapps\common\Team Fortress 2\tf\cfg "

(In the configs folder!)

It will look like this: Steam\steamapps\common\Team Fortress 2\tf\cfg\autoexec.cfg

If you are done you need to edit the autoexec.cfg with a programm like Notepad++
Delete the slashes from " exec nvidia "(when you opened the config).
Then it should look like this:
exec nvidia

(I dont quite know where steam is located in Linux systems since i run on win 10 but those folders should be the same lol).

Now if you restart tf2 it will automaticly load autoexec.cfg. 

(And no problem i like to help ppl with problematic systems or games to ensure the max comfort and fun).
And if you encounter problems go ahead and add me on http://steamcommunity.com/id/Wasmanr2/
I will help as much as i can!.

**Comment by furycd001** [comment]
Thank you so very much for all of that very helpful information :-) I simply cannot thank you enough for bringing these configs to my attention and for pointing me to the actually files :-) As soon as I get in from work later today I will be trying these files, so I will let you know if they work or not. Thanks also for the steam friendship offer :-)

**Comment by Wasmanr2** [comment]
No problem !
(I should be a forum support lol)

**Comment by kisak-valve** [comment]
@Wasmanr2, on Linux and Mac, Source 1 games including TF2 internally translates DirectX 9 to Opengl 2.1 + SRGB using the ToGL.

**Comment by Wasmanr2** [comment]
Ahh intresting didnt know that.
I thought the user needed to add a -gl launch parametr.
Seems not heh.
Thanks for the information.

**Comment by furycd001** [comment]
HI

Installed both of the files linked to above. TF2 now fails to even boot to the main menu. Inside steam I am told that TF2 is running but nothing appears on screen, nor does a task appear in my taskbar. I had to kill steam manually via terminal...

**Comment by Wasmanr2** [comment]
Hm.
Ok Sorry about that, forget the configs (I couldn't predict that this would happen tho).

So lets see, to fix this simply **delete** the config files you added.
(autoexec.cfg and nvidia.cfg)

Then go to the games library of steam.

==>  https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947&l=english
(In case if you dont know how to set launch parameters for tf2 i linked the guide of steam how to do it).

**vv Your binds will be reset if you set anything like that vv**
Then add the following launch parameter for the game Team Fortress 2.
-autoconfig 

This will restore video and performance settings to default for the current hardware detected. 

Ignores settings inside any .cfg files until this parameter is removed.

Then hit Ok and start tf2.

After you start tf2 once let it load and then close it again then delete the -autoconfig from the launch parameter.

After that lower your graphic settings.

@kisak-valve Does changing -dxlevel to 81 would make any changes in fps/stability or does the translation only applies for dx9?

**Comment by furycd001** [comment]
I didn't expect that to happen lol. Yea I went ahead and deleted the files when I found they didn't work. Thank you for that new piece of information. I will try it tonight and will let you know if it works or not.

**Comment by kisak-valve** [comment]
@Wasmanr2, my understanding is that -dxlevel has no effect when ToGL is in use. ToGL supports a subset of DirectX 9 and is not expected to cover other spec iterations of DirectX.

**Comment by Wasmanr2** [comment]
Alright thanks!

**Comment by Wasmanr2** [comment]
@furycd001 did lowering graphics + using -autoconfig worked or do you still having this issue?

**Comment by furycd001** [comment]
Sorry for not replying sooner, but it did not work :-( Just going to assume that after the most recent update I'm now running out of ram...

**Comment by furycd001** [comment]
This issue can be closed as I think my laptop no longer stands up to the requirements anymore. Buying a new laptop in a few months so won't be long without TF2...

**Comment by Wasmanr2** [comment]
I rather recommend you to buy a PC rather then a notebook especially for games like tf2 @furycd001 .
@kisak-valve you may close this as the last comment stated.
