### ISSUE TITLE
[TF2] [Feature Request] Disable voting for the previous map in casual matches

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2239]
This was done in CS:GO, and could improve the player base for lesser played maps and game modes.

**Comment by hahagoni** [comment]
A counter-argument would be that lesser played gamemodes (especially the ones with fewer maps) would be played even less (and not all of them are so underplayed without a reason). Also, maps like cp_degrootkeep would last way too short, thus less people would even que for it in the first place.
Bad maps like cp_junction or ctf_2fort could just be disabled to distribute those players among other maps (that would probably be controversial, though).
If maps were ordered in a way that favors better maps over bad ones, that'd lead to a much healthier player distribution.

**Comment by SnowshoeIceboot** [comment]
If you are going to disable voting for the same map, then add back the extend map vote and timelimit instead of the 2 round thing for people who want to play the same map longer.

**Comment by thecakeisalie25** [comment]
I'll add my 2 cents. Generally, when I queue up for a map, I want to play that map. It would infuriate me if i had to re-queue after every single game. Maybe allocate some servers to a "all map" rotation, where players are presented with a list of maps after the game ends, and find/create an algorithm that favors smaller maps as well as big ones, so that it doesnt turn into another set of 2fort servers. Or, pick a random set of 3 maps and present them for voting, kindof like the original idea.
