### ISSUE TITLE
[TF2] [Linux] Strange Random Crashes

### ISSUE THREAD

**Issue by PigLadAl** [ValveSoftware/Source-1-Games#2275]
Hello. I have getting these weird crashes on TF2. When I boot up the game and join a server, I am able to play for usually around half an hour before the game starts stuttering heavily for around 5 seconds, and then quickly crashes to desktop. After this happens, Steam crashes as well. Sometimes the game crashes after around over an hour, but sometimes the game crashes within a minute of me joining a game. I use Linux Mint 18.1 with LXDE, but I also get the same crashes in MATE. I use Conmanglia's Toaster config and mkhud, but I have been able to replicate these crashes without those installed. I have tried verifying the game cache and reinstalling TF2, neither have seemed to fix the problem. I haven't been able to find anything about this on the internet, so if someone could tell me how to get the game to have some sort of log output when this happens and where to find it, that would be greatly appreciated. Thanks!

**Comment by kisak-valve** [comment]
Hello @PigLadAl, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by PigLadAl** [comment]
Here.

<script src="https://gist.github.com/PigLadAl/38555ab41b7df407e0dd9e12e5efb93d.js"></script>

**Comment by kisak-valve** [comment]
It's highly likely you are running out of virtual memory space. The heavy stuttering is coming from the system using swap shortly before hitting the 4 GB limit which all 32 bit applications have. By the nature of the Intel graphics implementation, this limit is shared between the game and mesa.

This issue is being tracked at #2212 and you may be able to delay or avoid running out of virtual memory by lowering your graphics settings.

**Comment by Nephyrin** [comment]
Closing this in favor of #2212
