### ISSUE TITLE
[TF2] Update Replays to no longer use QuickTime

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2276]
Replays require Apple QuickTime or an equivalent to render them, as they use the .mov format. This is a security vulnerability as Apple no longer supports QuickTime on Windows and hasn't updated
it since 2016.

**Comment by stevethepocket** [comment]
Does it require you to install QuickTime separately to make this feature work? I was under the impression that the encoder (as a standalone product) is only available with QuickTime Pro, which I've definitely never had. If it's embedded in the game, lack of support from Apple would the least of our problems since no doubt they haven't updated the in-game copy since 2011.

At any rate, do you know what codec it uses? .MOV is only one of several container formats for what is typically H.264 video and AAC audio; both are industry standards and many encoders are available, including open source ones (whether Valve, a for-profit company using a closed-source engine, would be at liberty to license them is another matter).

**Comment by FindTheBorealis** [comment]
Yes, it needs QuickTime installed to render the Replay. I was using QT Lite, uninstalled it and couldn't 
render a Replay. 

From the TF2 Wiki:
"The save feature supports rendering of replay files with two codecs (H.264 and MJPEG-A) with 5 preset resolutions (480p, 720p, 1080p, Web, and iPhone). Alternatively, the replay file can also be saved to raw files in the form of a .tga sequence and an accompanying .wav file. This method renders each frame in the video to an individual .tga file at maximum quality and renders the audio for the scene to a .wav file. The sequence and the audio file can then be encoded together using a video processing program such as VirtualDub."
