### ISSUE TITLE
[TF2][Linux] Unable to install TF2 on Antergos

### ISSUE THREAD

**Issue by hatani** [ValveSoftware/Source-1-Games#2291]
Hi, I am not able to install TF2 repeatedly under under Steam running on Antergos Linux. 

Printscreen of error at the end of download is attached. I've attached steam log file as well, there are many errors related to corrupted files.

I tried to:

1. reinstall TF2 several times
2. clear download cache
3. delete whole folder under Downloading directory and redownload again
![basehaptic](https://cloud.githubusercontent.com/assets/740982/26800255/eb442f94-4a38-11e7-87d2-f6e4e2123c38.png)
[content_log.previous.txt](https://github.com/ValveSoftware/Source-1-Games/files/1053015/content_log.previous.txt)

**Comment by kisak-valve** [comment]
Hello @hatani, what filesystem is TF2 being installed to?

**Comment by hatani** [comment]
Hm, now this might be it actually:

/etc/fstab:
UUID=B612A04012A00807 /mnt/steam_sdb2 ntfs defaults 0 2

mount:
UUID=B612A04012A00807 /mnt/steam_sdb2 ntfs defaults 0 2

**Comment by kisak-valve** [comment]
This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4800 and you should be able to workaround this issue by mounting the ntfs partition with defaults,exec,uid=1000,gid=1000 (from https://github.com/ValveSoftware/steam-for-linux/issues/4800#issuecomment-271763278).

Closing in favor of the existing issue report.

**Comment by hatani** [comment]
Thank you SO much Kisak! That solved the issue (in Victor Vran too actually!).
