### ISSUE TITLE
[TF2] Advanced Options tooltips blank

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2340]
As of the Jungle Inferno update, the Advanced options tooltips are blank and stretch to the top
of the options window.
Example when hovering over fast weapon switch:
![20171021105255_1](https://user-images.githubusercontent.com/24868101/31853482-c16c334c-b64e-11e7-9b3f-db70ec78e206.jpg)
I don't know if custom huds are affected, since updated huds aren't modifying the main menu for now.

**Comment by FindTheBorealis** [comment]
After further testing, the tooltips show correctly until the "Play a hit sound everytime you injure an enemy"
option is hovered over, then all tooltips will be bugged until the window is closed and opened again.
This seems to happen every time the window is closed and opened.

**Comment by CriticalFlaw** [comment]
The bug is caused by missing tool-tip text for the "Contracts UI" option. This can be fixed by in adding `Tooltip_TF_Contract_Progress` to **tf_english.txt** 

![fix](https://user-images.githubusercontent.com/6818236/42914074-527a4fe4-8ac6-11e8-8eec-81078656e96f.png)


![20180718200609_1](https://user-images.githubusercontent.com/6818236/42914028-11a6b868-8ac6-11e8-9ccd-93fda912da3f.jpg)

**Comment by FindTheBorealis** [comment]
Closing as this has been fixed in the 2019/03/26 update, thanks @CriticalFlaw
