### ISSUE TITLE
MSAA related crashing of TF2 on Skylake and Kabylake

### ISSUE THREAD

**Issue by atoms118** [ValveSoftware/Source-1-Games#2418]
Alrighty, so since the Jungle Inferno update, I have not been able to play TF2 at all. The game will crash after entering a match, sometimes immediately, and sometimes it will be a couple minutes. The game is also extremely laggy.

I have not been able to get any errors, as my entire computer freezes, and I am forced to do a force shutdown (At least, I haven't found anything in /var/log/syslog. If there's somewhere else I can get logs, please let me know). Not only does the screen freeze, but the last 1 second or so of audio loops over and over until I power off my laptop.

Now, I am running it on a laptop with only an i7 and Intel HD, but on the other hand, the game ran fine for me before the update, so...?

I am running Ubuntu 17.10 (Tested on Wayland and Xorg)

Thank you for your time

(Note: The game ran fine on my computer before the update, but I was also using Ubuntu 16.04 before so...)

**Comment by kisak-valve** [comment]
Hello @atoms118, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

In general, no opengl application should be capable of freezing the system. If it does, that hints that there is a driver issue. Are you able to ssh into the laptop after this issue appears? If you can, then check dmesg if there any hints as to what's going on here.

**Comment by atoms118** [comment]
[Here is the system information thing](https://gist.github.com/atoms118/34c8ddd45847c89fa23dc0e8ebc4752b)

I will try to SSH into my laptop once I get home, thanks for the suggestion

**Comment by nightsky30** [comment]
@atoms118 My sympathies, I've experienced the same issues.  There appear to be multiple crash issues with Intel graphics drivers.  I can say changing the [MSAA](https://github.com/ValveSoftware/csgo-osx-linux/issues/1509) and Anistropic filter settings to something other than "None" have helped with the worst crashes (preventing me from even starting a match), but there appear to be at least [three](https://github.com/ValveSoftware/Source-1-Games/issues/2234) [other](https://github.com/ValveSoftware/Source-1-Games/issues/2212) [issues](https://github.com/ValveSoftware/Source-1-Games/issues/2310), and they are not presenting many hints.

**Comment by atoms118** [comment]
[Here is the output from dmesg](https://gist.github.com/atoms118/8f8b9b56e7fde0170eed851e08dced34)

SSH continues to work after my game has frozen. In fact, I have discovered that the game will stop and my computer will start working again after a couple minutes (As indicated by the dmesg log). I admit, this is starting to look more like an issue with Ubuntu 17.10 rather than TF2, but please give me your thoughts

**Comment by kisak-valve** [comment]
As @nightsky30 suggested, check if you have MSAA set to none and if it is, try to reproduce the issue with 2xMSAA set. If that helps, then it strongly suggests your issue is the same one being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1509 and https://bugs.freedesktop.org/show_bug.cgi?id=102435.

**Comment by atoms118** [comment]
Ah, yes, switching to 2xMSAA does more or less fix things. The game is still unplayable laggy, but I think I will read the links you gave first, rather than keeping this open. Thank you for the help! I will leave you the honors of closing the issue

**Comment by DeltaResero** [comment]
I can confirm that this is also an issue for Haswell too (tested with i5-4200m). To no surprise, even using Paulo Dias, padoka PPA didn't help any. This was tested on amd64 Kubuntu 17.10 with both beta[prerelease] and normal version of TF2 many times since the Jungle Inferno update and it results in the same outcome. Works fine in Windows except it requires Vsync enable or else there is severe tearing, but in Kubuntu 17.10 it crashes upon entering a game with MSAA disabled. Enabling it, it works enough to get into a game, but it quickly runs out of graphics memory and crashes and is extremely laggy till it does. It did however work in the first days of the Jungle Inferno update when I was using Kubuntu 17.04 back in late October, but a lot of textures were missing and it was even more laggy then now.

**Comment by kisak-valve** [comment]
Hello @DeltaResero, the identified driver regression being tracked in this issue tracker only applies to Skylake and Kaby Lake.

Please open a separate issue report as your MSAA-related regression with Haswell needs to be investigated separately and should also be brought to the attention of the video driver vendor if it has not been already.

**Comment by atoms118** [comment]
Hi, I'm a bit confused. I have seen the thing about Mesa, but

- Is this purely a Mesa issue and if not
- Is this going to be patched

I've already seen that supposedly Mesa will be fixed in version 17.3, but I'd still like to know if this was actually an issue with Source or just a pure Linux thing

**Comment by kisak-valve** [comment]
This is a mesa/intel driver issue, and mesa 17.1.x is not affected.

**Comment by atoms118** [comment]
Thank you! Should this issue be closed then?

**Comment by kisak-valve** [comment]
I left this issue open as a reference pointing to the upstream report. At this point there's no action to be taken by a TF2 dev, so it doesn't really matter if the issue stays open or not.

**Comment by kisak-valve** [comment]
This is now fixed upstream in 17.2.7 and 17.3.0.
