### ISSUE TITLE
[TF2] Fullscreen store item preview overlaps with the top UI bar

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2443]
The top bar hides the button to pick the red team partially, the zoom button, and the close button, meaning you have to press the escape key to exit the preview and go back to the main menu. The backpack fullscreen preview is sized correctly.

**Comment by CriticalFlaw** [comment]
The fix is to go to **resource/ui/econ/v2/storepreviewitempanel_fullscreen.res** and change the ypos values of **ZoomButton**, **TeamNavPanel** and **CloseButton** from 10 to 30. https://github.com/CriticalFlaw/TF2HUDFix/commit/b5cc9d297529e4fabee24f129d0088607c0072e2

**BEFORE:**
![20180826125826_1](https://user-images.githubusercontent.com/6818236/44630713-11629d80-a930-11e8-935f-a240458f124c.jpg)
**AFTER:**
![20180826125916_1](https://user-images.githubusercontent.com/6818236/44630714-145d8e00-a930-11e8-8006-77e28caaf51c.jpg)

**Comment by FindTheBorealis** [comment]
Closing as this has been fixed in the 2019/03/26 update, thanks @CriticalFlaw
