### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by KisakPt2** [ValveSoftware/Source-1-Games#2478]
Spam intentionally removed by moderator.

**Comment by lilvac** [comment]
csgo 
Hey boy, come here _I said to him._ Y-y-yes boss? _he replied._

I hear you wanted to be moved over here into the CS:GO section

T-that's right..

_His voice cracked at the end of each sentence. What a beta I thought to myself._

Well anyway, here's your big chance, kissakk, you need to port this here Accept Button shit over to Linux. You know Linux right?

Yes, I installed gentoo, bazinga

Uhh. Ok. Well get to work, if you need help just skid off doom 3, that runs on Linux right? Nevermind. Get out of my office before I call security

Right away Sir!

_I got the code back a couple weeks later and after another 3 months we were able to get it compile._

This is utter shit kisssassk, where did you learn to program?

From Devry Univerisity sir!

Well shit, head over to learncpp and finish all their lessons and come talk to me again regarding your CS:GO position. In the meantime, you can be my github-slave.

Gee boss, you really mean it? Thanks a lot! Let me call my BF and give him the news

No time, kissass, we gotta head over into the recording studio to meet with Soulja Boy for the new half-life 3 OST. I want you to get back to work ASAP.

Alright.

**Comment by lilvac** [comment]
hey you, yea you _I said to him._

y-y-yes boss? _he replied with a pretty fragile voice_
We're short on people on the vac team because everyones working on Dota 2 and Half Life 33, are you maybe inter-

Y-y-yyess please _said he to me. What a beta I thought to myself_

Alright kissskk, here's your chance to prove yourself, we have a problem with these "catbots" - do you think you'd be able to get them banned?

I-i-idduno he said

You know Linux right?

Yes, I installed gentoo, bazinga

Uhh. Ok. Well, get the work, just skid it off BattlEye or something, that runs on Linux right? Nevermind. Get out of my office before I call security

Right away Sir!

_I got the code back a couple weeks later and after another 6 months we were able to get it to compile._

This is utter shit kisasksss, how did you detect it?

I just looked for the catbot username, sir!

Isn't that kinda inefficient? Well, won't fix better ship it before end of 2017 or the guys over at /r/tf2 will get mad again. Head over to learncpp and finish all their lessons and come talk to me again regarding your VAC position. In the meantime, you can continue to be my github-slave.

Gee boss, you really mean it? Thanks a lot! Let me call my BF and give him the news

No time, kissass, we gotta head over into the recording studio to meet with Soulja Boy for the new half-life 33 OST. I want you to get back to work ASAP.

Alright.
