### ISSUE TITLE
[TF2] Feature Request: Make Pyro primaries less than extremely forgiving 

### ISSUE THREAD

**Issue by ldesgoui** [ValveSoftware/Source-1-Games#2485]
Hello,

Post-Jungle Inferno, playing with and against Pyro feels extremely cheap, the weapons are extremely easy to use and part of it is due to the massive collision boxes for the flame and fireball particles.
I think those settings are more representative of which particles should or shouldn't collide:
`tf_fireball_radius 10` and `tf_flamethrower_boxsize 2`

Thanks

**Comment by Exaeta** [comment]
Pyro is too strong right now and completely overpowered. Pyro's DPS is comparable to heavy. Heavy mainly had hitscan which is easier to aim, and pyro lacked this, but was faster. This is a problem now, Because: 1. You don't have to aim. and 2. the dragon's fury is fast enough that the fact it isn't hitscan doesn't really matter much.
So now heavy is just an inferior pyro but with more HP.

**Comment by kisak-valve** [comment]
Hello @ldesgoui, @Exaeta, this should have improved with the [2018-03-28](http://www.teamfortress.com/post.php?id=38643) TF2 update. Please retest.

**Comment by agrastiOs** [comment]
@kisak-valve The situation with the Pyro is much better now and this issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by ldesgoui** [comment]
Agreed, thanks VALVe :)
