### ISSUE TITLE
[TF2] tf_damage_disablespread does not affect fall damage

### ISSUE THREAD

**Issue by ldesgoui** [ValveSoftware/Source-1-Games#2489]
Hello,

`tf_damage_disablespread 1` does not remove falls damage's 20% variance (according to Wiki)

Thanks

**Comment by stephanieLGBT** [comment]
this can be easily fixed by removing `flFallDamage *= random->RandomFloat( 0.8, 1.2 );` from [here](https://github.com/VSES/SourceEngine2007/blob/master/se2007/game/shared/tf/tf_gamerules.cpp#L2048
) or checking value of tf_damage_disablespread and calculating random 20% based on that

simple example sourcemod implementation [here](https://github.com/stephanieLGBT/tf2-FallDamageFixer/blob/master/addons/sourcemod/scripting/tf2FallDmgFix.sp)

**Comment by nosoop** [comment]
Addressed in the update on 2022-07-07:
> - Added a game server setting, "tf_fall_damage_disablespread", to disable random fall damage (default: 0)
