### ISSUE TITLE
[DoDS] Unable to debug with GDB

### ISSUE THREAD

**Issue by APGRoboCop** [ValveSoftware/Source-1-Games#2522]
Hello I'm trying to test and debug a addon for DoD:S but it appears that using "$ gdb srcds_linux" followed by using "$ (gdb) run -game dod +map dod_orange_gunna_arena +ip xx.xx.xx.xx -port 27015 +maxplayers 16 -insecure -nohltv -norestart -debug +sv_setsteamaccount xxxxxxxxxx" fails for some reason. I've checked in /bin folder for dedicated_srv.so to see if it's missing but its not. I don't understand what but this is what I got:-

> $ (gdb) run -game dod +map dod_orange_gunna_arena +ip xz.xx.xx.xx -port 27015 +maxplayers 16 -insecure -nohltv -norestart -debug +sv_setsteamaccount xxxxxxxxxx
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
> Failed to open dedicated_srv.so (dedicated_srv.so: cannot open shared object file: No such file or directory)
> [Inferior 1 (process 22346) exited with code 0377]
> (gdb) 

I'm using Xubuntu 14.04 x64 LTS with Intel Quad Core Xeon and 16GB DDR3 RAM. And yes I did install those ia32_libs packages and add arch i386 etc...

**Comment by kisak-valve** [comment]
Hello @APGRoboCop, Steam adds `<gamefolder>/bin` to LD_LIBRARY_PATH for all games.

You could run gdb with `LD_LIBRARY_PATH="$LD_LIBRARY_PATH":<gamefolder>/bin` or run gdb with `<steam folder>/ubuntu12_32/steam-runtime/run.sh` in order to have a similar environment to how the game is run from steam or run steam with `GAME_DEBUGGER=gdb steam` from a terminal and start the game with steam.

**Comment by APGRoboCop** [comment]
That seemed to worked thanks!
