### ISSUE TITLE
[TF2] Crash everytime I join a match

### ISSUE THREAD

**Issue by buyBread** [ValveSoftware/Source-1-Games#2528]
At first I wasn't able to even join I just crashed when the game was trying to load the map in, I reinstalled tf2 after that and now I can join a match but it crashes the moment I join.
OS: Arch Linux
Desktop/Window Manager: i3wm
[System Information](https://gist.github.com/buyBread/6f305453975205c28e40e0ea3f755e90)

**Comment by buyBread** [comment]
Yes after the game crashed I found these in `/tmp/dumps/`.
[crash.zip](https://github.com/ValveSoftware/Source-1-Games/files/1744647/crash.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in vphysics.so.

There's a lot of stdout errors related to dxsupport_override.cfg and glbaseshaders.cfg. Can you find and remove these files in the TF2 install dir, then verify the game files and see if that makes a difference?

**Comment by buyBread** [comment]
Strange I can't find these files in the tf2 install directory

**Comment by incognico** [comment]
How does it crash? I see you are using Intel HD graphics, I have a similar issue on Windows. The last time I played TF2 (just after the MM update) I could play on casual servers just fine without problems but as soon as I tried to connect to a matchmaking game the sound would loop and the game will hang at the loading screen. Someone suggested it was because of my -dxlevel launch option being too low for MM servers. Not sure if I have verified that back then.

**Comment by Tiagoquix** [comment]
@buyBread Please retest using the updated 64-bit + Vulkan version.

**Comment by buyBread** [comment]
Unable due to not having the laptop on which the crash occurred. Regardless, if I remember correctly, the issue was on my end after all. It was too long ago now, so I can't recall what the cause of it was, but I think it was audio related? Not sure why I didn't come back here to close the issue back then after resolving it.
