### ISSUE TITLE
[TF2] Getting awarded 0 MMR when winning TF2 Matchmaking

### ISSUE THREAD

**Issue by NetroScript** [ValveSoftware/Source-1-Games#2566]
At some point while playing TF2 Competitive Matchmaking I only got 0 MMR after a win. Before (shortly after getting ranked as Rank 9) I got awarded MMR normally. 
If I now lose a game, I lose 1 MMR, always, If I win a game, I always get 0 MMR. Meaning even after winning 5 games in consecution my total MMR remains unchanged. In winning matches I had a diversity of "usefulness" for my team. Meaning I was bottom scoring, top scoring, had no medals, had multiple gold / silver / bronze medals. All of these had no influence to my MMR.
Of the people I asked no one else is experiencing the problem. They all gain at least ~9 MMR every win and also lose more than 1 MMR.

Losing 1 MMR despite mediocre accomplishment
![20180413190502_1](https://user-images.githubusercontent.com/18115780/38750783-520bf168-3f56-11e8-9b18-efe772d3ec97.jpg)

Getting 0 MMR despite winning
![20180413200607_1](https://user-images.githubusercontent.com/18115780/38750852-91d67a2a-3f56-11e8-9c3a-e43e25fe101d.jpg)

If you want to check anything - my steam account is http://steamcommunity.com/id/Jack_5515/

**Comment by FindTheBorealis** [comment]
A Valve dev [explained](https://forum.facepunch.com/f/tf2/sqsb/TF2-General-Chat-and-Speculation-Station-V6-Year-of-the-Guard-Dog-SURVEY-IN-OP/178/#postcvcktd) why this can happen, it's a result of having a lot of people still in placements, they said it should become rarer as the amount of people in placements goes down. They're looking into having a win/loss always give or lose a minimum mmr instead of less than one, which gets rounded down to zero causing this.

**Comment by NetroScript** [comment]
Sounds interesting, but is strange that I probably had like 50 games by now where not a single game gave me MMR. And what I think is strange is that I queued with some players, and in the same games they got MMR. If the fault was the high uncertainty rate of a player, wouldn't the friends I queued with also get 0 MMR?

**Comment by Nephyrin** [comment]
@NetroScript MMR is calculated on a per-player basis, not per-party.  (Though it does take into account that you queued with a party member).

In your screenshot, there are only two non-placement players in the match.  This is a rather exact example of the low-certainty issues -- placement players will have the least-certain ratings by design.

Quoting the MMR text from the above link, as it is helpful context:

>Our MMR system, based on the Glicko system, has an inherent uncertainty value it assigns to players ratings, which is factored in when computing win/loss changes.
>
>What is happening here is many players in the system still have high uncertainty ranges that, when combined with a player who has a low-uncertainty rating, ends up in very small, or even 0, MMR adjustments on win or loss.  Essentially, the system is saying that, given the balance of team-vs-team ratings and their given uncertainties, it does not believe your resulting MMR should be adjusted based on this result (or, more accurately, the resulting MMR adjustment is below 0.5, and rounds to zero).
>
>We realize getting a 0 MMR adjustment is not the greatest experience.  We expect this to become exceedingly rare as the portion of placement players drops, as the system tends to only produce this result when a number of low-certainty players are gathered together.  We may also end up tweaking the math to ensure players always gain/lose a minimum MMR, depending on the feasibility.

There is a knock-on issue here, wherein having a rather high MMR will place you further from many well-placed players, but placement players will still be matched with players of various rankings.  This means you are more likely to get a game with a lot of placement players when the population is still heavily in placement and your rank is somewhat uncommon.

So, while the ultimate fix is having a smaller portion of the playerbase in placement at any given time, we are looking at tweaking the math here to give a better experience.

**Comment by NetroScript** [comment]
@Nephyrin 
![20180516225236_1](https://user-images.githubusercontent.com/18115780/41674601-ccfa82a0-74c0-11e8-939d-e0499bfb37d8.jpg)
If we take a look at this screenshot you can see that only 2 people don't have a rank, So I would assume that for the MMR system this was a "balanced" match.
I recently stopped playing Valve Matchmaking and then started playing again (after I guess multiple weeks) and at that point I lost MMR and gained MMR again. Before I had multiple hundreds (I didn't count them, but I lost 1 MMR per game and ranked down 2 ranks and that were only the games I lost) of matches where I never got MMR. So I would assume the chance of me never having a match that had low uncertainty values is really low. That is why I still would assume that there must be some bug or the MMR system needs to be adjusted. In my opinion it is strange that I now get MMR after not playing for a longer time, so I would see a connection there.
But of course asking others who also had / have the problem with the 0 MMR could help (but no one of my friends who also played the Matchmaking experienced the same problems, so I can't ask them).
![20180618212954_1](https://user-images.githubusercontent.com/18115780/41674940-9149ad98-74c1-11e8-9dea-6989d67e56b5.jpg)
Here is me getting MMR again, despite only 4 ranked players.

**Comment by Nephyrin** [comment]
@NetroScript 
The way confidence interval works is more over-time than a specific match - in this case, your confidence interval widened from previous matches, which resulted in subsequent matches adjusting your MMR further, even if the subsequent matches were less-confident over all.

I took a look at your match history, and don't see anything that would indicate a bug -- though I can confirm you are seeing a lot of 0MMR games.  The next update has some changes to the algorithm that should result in a better experience, and we will continue tweaking things as more players exit placement.

**Comment by NetroScript** [comment]
I played 10 games since the update for now and didn't experience problems yet, although 10 isn't so much. I will probably get back after playing more.

**Comment by Nephyrin** [comment]
The June 26th update should have resolved all instances of this.
