### ISSUE TITLE
I'm getting kicked from TF2 casual games for no reason

### ISSUE THREAD

**Issue by linopi** [ValveSoftware/Source-1-Games#2599]
Since yesterday I've been getting kicked from casual games with #TF_MM_Generic_Kicked (Removed from match by system) reason. I always get kicked no matter what I do - play the game or do nothing at all.

CL output: Not necessary

Steps to reproduce this issue:
1. Queue for Casual mode, find match and join it.
2. **Get kicked - that's the issue.**

Hardware information:
Debian Buster x64 (liquorix latest version kernel)
lightdm, cinnamon
nVidia GeForce GT 740 (driver version 390.48)
lvm, encryption, filesystem is ext4.

![image](https://user-images.githubusercontent.com/39243456/39969950-6f6c47c8-5705-11e8-8380-7c040ef5b1f4.png)

**Comment by AutismGaming228** [comment]
Can confirm, getting kicked since yesterday randomly.

**Comment by buyBread** [comment]
same on arch with openbox window manager

**Comment by delet-this** [comment]
Same issue on arch linux, zen kernel, i3 window manager, steam runtime.

**Comment by YouveGoatToBeKittenMe** [comment]
Glad to know this isn't just me, I was really confused. Void Linux.

**Comment by jaydipmodhwadia52** [comment]
Also having issues. Am on Ubuntu.

**Comment by Marc3842h** [comment]
Can confirm this issue is persistant on Arch Linux with Gnome under Wayland. The playerbase is already shrinking and by not even allowing normal people to play, you're making it even smaller.

**Comment by kritzsie** [comment]
Can confirm on Arch Linux with the latest package updates as of this post. This is the second time I've had major issues with Steam and TF2 in less than one year. Something tells me they don't want to see people playing this game at all.

**Comment by AzureAzel** [comment]
I can confirm that this also happens on Windows. It seems to be a global issue. This happened to me yesterday evening, but has since not occurred. It appears to be random.

In addition, I've seen an overabundance of people getting disconnected with this reason. It usually occurs when you queue for a new casual match whilst you're already in one, but in this case it just kicks you from the game despite never starting a new queue whilst already ingame. It's safe to assume that the people I've seen getting "removed" from the match are getting kicked due to this bug. Or whatever this is.

There's also a reddit thread that appeared recently about this: https://www.reddit.com/r/tf2/comments/8j0pqw/keep_getting_removed_from_match_my_system_every/

**Comment by kisak-valve** [comment]
Good day, I've received a note from the TF2 team indicating this issue was resolved server side and if anyone is seeing this issue, please use [Steam Support](https://help.steampowered.com/en/) so that they can check account-specific details.
