### ISSUE TITLE
tf2: can't upload replays to youtube

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/Source-1-Games#2694]
The console log says:
Error: Protocol https not supported or disabled in libcurl

**Comment by Koterminus** [comment]
@kisak-valve This thread is a duplicate of #1511, which was opened in 2013 and closed some time later at the end of 2016 due to no longer being relevant. However, the actual problem that this thread was created for is still ongoing and is currently being tracked at #2277 with more information, so I think this can be closed.

**Comment by kisak-valve** [comment]
Thanks @Koterminus, closing in favor of #2277.
