### ISSUE TITLE
[TF2] Workshop maps missing soundscapes, sound overrides, custom sounds

### ISSUE THREAD

**Issue by nosoop** [ValveSoftware/Source-1-Games#2701]
I guess since this exists I'll report it here.  Seems to have more transparency than the game's built-in bug reporter where I reported this previously.

The following issues are present for Workshop maps in TF2:

* Sounds embedded in maps cannot be played on the client.  The engine reports the following error in the developer console:
    > Cannot figure out which search path %s came from.  Absolute path is %s

  It can be reproduced by running `map workshop/1171267245` in the server console to load the Workshop version of [Monster Bash].
* Soundscape and soundscript (sound override) files are not loaded in at all.  There are no "generic" variations of either, [unlike the `embed.nav` support for navigation meshes][embednav].
  * [I've written my own server-sided fix for this as a SourceMod plugin][soundfix], though it's obviously limited to sounds that are emitted from the server.

Unfortunately, these issues make for a subpar experience when playing Workshop maps.

[Monster Bash]: https://steamcommunity.com/sharedfiles/filedetails/?id=1171267245
[embednav]: https://tf2maps.net/threads/future-way-of-packing-nav-files-into-bsp-and-getting-them-to-work-properly-with-workshop-elsewhere.30583/
[soundfix]: https://github.com/nosoop/SM-TFWorkshopSoundsFix

**Comment by worMatty** [comment]
MvM pop and res files aren't found either. I don't know about other files like surface properties, particle manifests and so on.

I would prefer to be able to continue to use the standard naming convention for these files instead of needing to rename them to 'embed', which adds more work to the release process. We are able to load custom materials and models that are packed in the BSP, so I do not understand why mymap_level_sounds.txt, soundscapes_mymap.txt and mymap.nav aren't picked up when the menu photo images and mymap.txt apparently are.

**Everything below is non-technical, opinion stuff:**

When the map workshop for TF2 came out it could have been revolutionary for mappers, players and server operators but the implementation seems to be half finished. Server operators could have gotten rid of their FastDL servers and would know their maps would always be up to date, players would have more free hard drive space and would benefit from faster downloads, mappers could have shown their work side by side with other maps in a central place that was integrated with the Steam community.

At the moment, subscribing to maps has no benefit to players and I suspect that the majority do not realise that subscribing downloads the map to their Steam files. There is no easy way for them to play these maps, and no integration with the Workshop and the Steam server browser. Players need to get the nine digit map ID number _from the URL_ to play offline.

As a mapper, I would love to use the Workshop as the main place I showcase my work and interact with players and server operators. I would love to advise server operators to use the Workshop to host my map, and encourage everyone to feed back any issue no matter how small so I could release an update and be sure that everyone receives it. Community organisations and their eager mappers would hopefully be less likely to produce their own unauthorised 'fixed' versions and more inclined to complain to me, and I wouldn't need to limit the frequency of updates to avoid causing confusion and extra work for server operators.

Five years ago I posted a couple of guides for using the Workshop which may be useful for anyone who doesn't understand some of the terminology or processes.
https://tf2maps.net/threads/the-tf2-maps-workshop-for-map-authors-and-players.24614/
https://tf2maps.net/threads/tf2-map-workshop-server-configuration.24585/

**Comment by nosoop** [comment]
From what I can gather (best guess in current tired state, doesn't mix well with staring at disassembly):

- surface properties have filenames based on the file `scripts/surfaceproperties_manifest.txt`?  (I'm not a map maker; let me know if that's incorrect.)  It should perform a lookup in the game and find it in the BSP
- particle manifests / gamesounds / soundscapes / navmeshes all use the full map name, not the cleaned-up display name; they're all either within shared client/server code whereas photos / map.txt is purely client (I think; what is the latter used for?)

Big +1 on the opinion; as a server operator myself I had that very same sentiment when the Workshop came out.  I still do &mdash; I source as many maps as I can through the original authors' Workshop submissions.

**Comment by nosoop** [comment]
FlaminSarge just pointed out to me / discovered that adding this line as a search path in `gameinfo.txt` causes sounds to *just work* on the client.
```
game+download   |all_source_engine_paths|../../workshop/content/440
```

Explanation:
> [11:12 PM] FlaminSarge: what's happening is, it's finding the files and all fine but it fails to add them to any sound cache
[11:13 PM] FlaminSarge: and because the sound cache is missing the client's just like 'lmao we found the file but it doesn't exist [...]'
[11:13 PM] FlaminSarge: when you add either of those things, it creates a sound cache in
[11:13 PM] FlaminSarge: either the 440 folder for the latter, or each individual workshop folder [if you use a wildcard so it looks up all the subdirectories (however, they're only iterated on startup)]
[11:13 PM] FlaminSarge: and from there, sounds just work

**Comment by FlaminSarge** [comment]
First, I believe it'll be sufficient to just include 
```
game   |all_source_engine_paths|../../workshop/content/440
```
as we don't want to mark our workshop folder as the directory to store downloaded files in.

The reason the above `gameinfo.txt` change works is due to the engine's behavior in `CAudioSourceCache::LookUpCacheEntry` and, by relation, `CAudioSourceCache::Init`.
Source, by default, creates a sound cache for every single `game` search path that's available (as defined by `gameinfo.txt`), e.g. `tf/sound/sound.cache`, `tf/download/sound/sound.cache`, etc. This happens in `Init()`, but naturally, when the search path is the map BSP itself, it can't create any sort of sound cache inside it (`map.bsp/sound/sound.cache` is invalid).
However, when Source goes to play the sound file (more accurately, to get the sound's Info), it calls `LookUpCacheEntry` to check that the sound file belongs to _any_ cache, which means that the sound file must fall under any of the search paths that _have_ a cache.
For sounds that are embedded in BSP files, this also holds true, but, again, the BSP does not have a cache, so usually this would fail. However, maps in `tf/download/maps` (and `tf/custom/X/maps/`, etc.) fall under several different search paths: each folder under `tf/custom/` is a search path, `tf/` itself is a search path, and lastly `tf/download/` is a search path. Thus, when the sound coming from the map BSP are cached, they go into the cache belonging to the first search path they find. In the case of `tf/custom/X/maps/map.bsp/sound/test.mp3`, that cache is `tf/custom/X/sound/sound.cache`. In the case of `tf/download/maps/map.bsp/sound/test.mp3`, the cache at `tf/sound/sound.cache` gets used, as the search path for `tf/` has higher priority than the search path for `tf/download/`.
When a workshop BSP's sounds are loaded, `LookUpCacheEntry` has some trouble, because there's no search path that encompasses the workshop BSP (`steamapps/workshop/content/440/INDIVIDUAL_WORKSHOP_ID/map.bsp`). It fails and returns null, and the engine refuses to play the sound because it's not in any cache. When we add the above workshop path to `gameinfo.txt`, any and all workshop map sounds are now encompassed by that search path, which has a cache sitting at `steamapps/workshop/content/440/sound/sound.cache`. Thus, LookUpCacheEntry succeeds and the client's engine properly plays the sound.

**Comment by KaydemonLP** [comment]
Not sure how much this helps but...
From what I gathered in my own research, the methods for getting the map name used in soundscripts and soundscapes returns "workshop\map_name.ugcWorkshopID" instead of "map_name.bsp" when you load via workshop.
The test I did to conclude this:
1. Made a map, test.bsp
2. Uploaded it to the workshop
3. Got it's workshop ID
4. Packed soundscapes into
"scripts/soundscapes_workshop/test.ugc2257787721.txt"
Packed soundscripts into
"maps/workshop/test_level_sounds.txt"
( Reason level sounds don't have the workshop ID here is, I presume, because SoundEmitterSystem.cpp uses Q_StripExtension, which in this case would strip the .ugcID part )
5. Updated the original workshop submission with this new bsp.
6. Loaded up the map via "map workshop/2257787721"
Soundscripts and Soundscapes now worked.

Though this only loaded the scripts, it did not precache any new sounds, so only the ones that reused sounds already in the game worked.

**Comment by IzotopeDev** [comment]
I was really excited when I heard about this way of getting soundscapes/soundscripts working, however this did nothing for people looking to use custom embedded sounds through their soundscapes/soundscripts, because just like KaydemonLP said, this only works for existing stock sounds.

Fixing the workshop to load a map's scripts and cache its packed sounds properly would finally allow mappers to utilize the workshop's full potential.
Keeping your works up-to-date without versioning the filenames and distributing them to server operators so easily is very much what people want and need.

**Comment by 111112oo** [comment]
This is a fix I would really appreciate. I'm hesitant to put my maps on the Workshop because loading them directly from the Workshop would result in a broken version of the map in regards to soundscripts and such. I'm sure many others feel the same way. I've seen plenty of instructions in map descriptions to get the original map file to run instead because of this issue. I wouldn't be surprised if some maps are getting rated less due to broken sounds when loaded from the workshop.

Fixing this would benefit everybody; Valve, players and mappers.

**Comment by Berke111** [comment]
As a mapper, I am really hesitant to put my maps on the Steam Workshop cause of problems like this, I think could be good to fix these issues out, since I myself use this sound system on my maps from time to time.

**Comment by FlaminSarge** [comment]
Take a look at some of the server/clientside solutions in this thread and hope that Valve patches this sometime soon. Each of the issues described has either a serverside or clientside fix by this point, so worst case, as a mapper, direct people to the given SourceMod plugin for soundscapes/levelsounds to function properly, or to the relevant download for gameinfo.txt for custom sound files to work.

**Comment by nosoop** [comment]
Might be addressed in today's update; will recheck and close once confirmed.

> - Added support for custom sounds, soundscripts, soundscapes, navmeshes and particles in workshop maps

**Comment by nosoop** [comment]
With the `gameinfo.txt` hotfix removed, I've confirmed that:

- Custom background music on [`koth_variousartists`](https://steamcommunity.com/sharedfiles/filedetails/?id=657272466) works (IIRC this uses a soundscape).
- Custom sounds and overrides on [`pl_skirmish`](https://steamcommunity.com/sharedfiles/filedetails/?id=1351700929) work.

Along with the other Workshop map-related fixes and polish that landed with the recent updates, I think we've finally reached the point where maps downloaded from the Workshop are functionally the same as those downloaded via FastDL.
