### ISSUE TITLE
[HL:S] Closed captions don't caption Glock 17 and reloading noises.

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/Source-1-Games#2973]
Throughout the game, captions for Glock 17 firing and reloading noises don't appear even when closed captions are enabled. This was tested with English localization.

HL:S Version:
Build Label: 5377866 # Uniquely identifies each build
Network PatchVersion: 5377866 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version

System info here:
https://web.archive.org/web/20191207232514/https://pastebin.com/qJ5SPXg3

**Comment by kisak-valve** [comment]
Closing in favor of #2975.

**Comment by Yetoo1** [comment]
I meant #2975 to be strictly for 9mm pistol (USP Match edition) reloading noises. The Glock 17 in HL:S doesn't have reloading **and** firing captions. Also it's a different weapon. Unless you want to lump in the Glock 17 reloading caption with #2975 and have the firing caption for the Glock 17 a separate issue, I would recommend reopening this.

**Comment by kisak-valve** [comment]
I read this as the 9mm starter pistol is missing some closed captioning. This is effectively the same weapon slot as the USP in HL2, but by a different name. If a Source 1 dev has interest in tracking this separately or a fix ships that misses HL:S, we can re-open, otherwise I don't see any value in tracking HL:S separately for this particular issue.
