### ISSUE TITLE
[SDK] [Request] Looking for vbsp, vvis, vrad from 2005 SDK Beta

### ISSUE THREAD

**Issue by jokubasver** [ValveSoftware/Source-1-Games#3157]
Currently I'm working on modding the Original Xbox port of HL2. Looking at the episode1 Source SDK code, I saw some leftover xbox code for vbsp and vrad, however it is either not complete, or the BSP compile tools are too new for the OG Xbox (xbox used version 19 BSPs it seems). 

After digging around, it seems that this xbox code was added on **November 22nd, 2005** with the release of Source SDK Beta (first DoD:S SDK release) and it stayed up until **January 5th, 2006**.

Looking at old forum posts, I figured out that I am hunting for these versions of BSP compile tools, which (hopefully) include all of the OG Xbox code for compiling maps:
**vbsp.exe (Nov 17 2005)
vvis.exe (Sep 7 2005)
vrad.exe SSE (Nov 9 2005)**

**Anyone at Valve** - I'm pretty sure you guys have these in your archives or depots. Would love to have access to these old files again or better yet, those old versions of Source SDK Beta: https://developer.valvesoftware.com/w/index.php?title=SDK_Beta_Changelist&oldid=21059#Update_Wednesday_November_22nd.2C_2005_.28initial_release.29

**Comment by 1157** [comment]
Is there version here too new?

https://www.youtube.com/watch?v=F7adN-xAMoE

**Comment by jokubasver** [comment]
> 
> 
> Is the version here too new?
> 
> https://www.youtube.com/watch?v=F7adN-xAMoE

That seems to be just a modification to Source SDK Base 2006 to be compatible with Steampipe, the compile tools included with that are too new.

**Comment by Yetoo1** [comment]
@jokubasver You weren't able to find it?

**Comment by abasgames** [comment]
> Currently I'm working on modding the Original Xbox port of HL2. Looking at the episode1 Source SDK code, I saw some leftover xbox code for vbsp and vrad, however it is either not complete, or the BSP compile tools are too new for the OG Xbox (xbox used version 19 BSPs it seems).
> 
> After digging around, it seems that this xbox code was added on **November 22nd, 2005** with the release of Source SDK Beta (first DoD:S SDK release) and it stayed up until **January 5th, 2006**.
> 
> Looking at old forum posts, I figured out that I am hunting for these versions of BSP compile tools, which (hopefully) include all of the OG Xbox code for compiling maps: **vbsp.exe (Nov 17 2005) vvis.exe (Sep 7 2005) vrad.exe SSE (Nov 9 2005)**
> 
> **Anyone at Valve** - I'm pretty sure you guys have these in your archives or depots. Would love to have access to these old files again or better yet, those old versions of Source SDK Beta: https://developer.valvesoftware.com/w/index.php?title=SDK_Beta_Changelist&oldid=21059#Update_Wednesday_November_22nd.2C_2005_.28initial_release.29

maybe this ? https://github.com/smb123w64gb/source-sdk-2005-xbox

**Comment by smb123w64gb** [comment]
Ah yes, its abit hacky. Upgrading all the way from I think MSVC 2005 to 2020... 

I want to redo it for more modern SDK / Architectures. 
Xbox is 2006 just dummyed down for quick loading and more. Maps from 2006 and xbox is changing the lighting lump to the 2004 standard, and of course adding a new form of light maps.... There prob more to it I have yet to find. Other then that, I found AIN to be -1 on the number of hulls from 2006 (And not ascii like 2004).

I should prob post more about other discoverys somewhere, Else for quick testing got all files redirected from the xzp to the "D" drive of the xbox. This will not work on real HW since the XFat format does not support the Number of files/folders HL2 uses. Just good quick testing on CXbx-R
