### ISSUE TITLE
TF2 boots into small 640x480 window on startup

### ISSUE THREAD

**Issue by JacobJustice** [ValveSoftware/Source-1-Games#3481]
When booting the game, it loads into a small 640x480 window and mouse clicks are offset, not allowing me to interact with buttons in a normal way.

-fullscreen/-full does not work. -windowed -noborder does work, but the gnome taskbar and top bar display over the game (most likely a gnome problem not a tf2 problem)

Using `mat_setvideomode 2560 1440 0` in-game sets the game to fullscreen properly, but running that same command in autoexec.cfg does nothing on startup.

I am on Ubuntu 20.10 using nvidia 455.x drivers with kernel 5.8.18

**Comment by kisak-valve** [comment]
Hello @JacobJustice, you're probably seeing a GNOME 3.38.1 specific regression, the same as https://github.com/ValveSoftware/csgo-osx-linux/issues/2551 and fixed in mutter 3.38.2. Fedora 33 should have already gotten an update while Ubuntu 20.10 is waiting on https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1908158.

In any case, the issue tracked here was resolved in 2013 and issues with Team Fortress 2 should be tracked in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.

(repeating my response from https://github.com/ValveSoftware/steam-for-linux/issues/110#issuecomment-746462105)

**Comment by JacobJustice** [comment]
Thanks for the response, makes sense. Guess I'll just have to wait on the 20.10 fix.

**Comment by UAVXP** [comment]
You can close the issue now, as it doesn't relate to the game
