### ISSUE TITLE
Issues running Left 4 Dead 2

### ISSUE THREAD

**Issue by JJDDXx2** [ValveSoftware/Source-1-Games#3583]
https://user-images.githubusercontent.com/85652470/124697134-e94f6300-deab-11eb-980f-c548d66473f4.mp4

The current problem is that every single, single player mode produces the same results: Inability to run, no glows around players or items, no survivor bots spawning, and dying in one hit to both special and normal zombies- Multiplayer also produces mostly the same effects, without the issues of dying in one hit or the lack of survivor bots.

These issues persist after changing settings (in-game and in the game files), and uninstalling and reinstalling the game multiple times (with steam cloud on and off at different points, repeating on a completely different computer)

The entire game is glitched and after trying quite literally everything (Including speaking to Steam Support, and speaking to the creator of the RocketDude game mode), I have come to the conclusion, that this issue is the result of a glitch in the data saved for the game on my account itself, and I'm wondering if there's any way to have the majority of that data deleted without having my achievements removed?

If not, is there anything else I can do to fix this issue?

I can provide a video that displays exactly what my game looks like/what I have described in the above text

**Comment by mustymaster** [comment]
you can add video right now by clicking edit and dropping the video in the text bar. in that way we can help you more and also for sake of context because these stuff happen rarely.
but I would recommend a option:
first disable l4d2's syncing with steam cloud through properties of steam. then delete the cfg folder in the steam/steamapps/common/left4dead2/left4dead2.
now in properties of left 4 dead 2 in steam, under the general tab, you'll see a bar called launch options. type "-autoconfig" without the quotation marks.
then launch your game and close and verify your game through steam
if you still have the problem check your workshop items, maybe they are causing a problem and if they're not. sending your video is good option to observe the problem. thanks
from mustymaster, not valve(XD)

**Comment by JJDDXx2** [comment]
Video now added (single player game, no settings changed in game whatsoever)

**Comment by Tiagoquix** [comment]
Hi OP, is this still relevant as of 2024?

**Comment by kisak-valve** [comment]
Closing pending feedback.
