### ISSUE TITLE
[Portal] Credit issues in Portal 2 depending on video settings

### ISSUE THREAD

**Issue by TLPenn4** [ValveSoftware/Source-1-Games#3630]
When I reach the Credits of Portal 2, things are wrong depending on what my video settings are.

When I'm using max video settings, the credits are just a black screen as "Want You Gone" plays, and once the song finishes, the game just stays on the black screen and never transitions to the post-credits scene.
#
When I'm using minimum videos settings, the credits scene DOES show and transition to the post-credits scene, but the credits and lyrics to "Want You Gone" are displayed on the opposite sides for some reason. I've attached a screenshot for only the minimum settings issue because the max settings issue is just a black screen.

![620_20210721202131_1](https://user-images.githubusercontent.com/87838355/127181806-ffa5ffd2-846e-4c1a-8c38-f9ce81f8954d.png)

https://gist.github.com/TLPenn4/c16b7fcfb9f2c50e470572bf35bcf024

**Comment by kisak-valve** [comment]
Hello @TLPenn4, this issue is already being tracked at https://github.com/ValveSoftware/portal2/issues/105. Since this issue report is clearer than the original report, I've gone ahead and transferred it to https://github.com/ValveSoftware/portal2/issues/105#issuecomment-887646821.

Closing as a duplicate.
