### ISSUE TITLE
[TF2] item_teamflag OnPickup and OnDrop outputs don't track the right !activator entity when fired

### ISSUE THREAD

**Issue by SpookyToad2** [ValveSoftware/Source-1-Games#3679]
When some player picks up a flag, item_teamflag fires OnPickup output, but !activator target is item_teamflag entity itself, instead of player who's picked up this flag.

I made a [video showing the issue](https://youtu.be/wfEF3XHnwVc). Small map with trigger that enables third person view and item_teamflag entity at the center.
When OnPickup is fired, it sends `SetModelScale(2)` input to the !activator target.
Player should have become bigger, but instead item_teamflag became larger two times.
[The map's gist.](https://gist.github.com/SpookyToad2/2f81baa2af2a4b4e1ba77bf51e5decb9)

Console logs of logic:
```
(23.53) output: (item_teamflag,) -> (!activator,SetModelScale)(2)
(23.55) input : item_teamflag.SetModelScale(2)
```

How to reproduce the issue:
1. Get the example map from the gist.
2. Load the map.
3. Choose the team and class.
4. Type into console `developer 2;mp_waitingforplayers_cancel 1`.
5. Pick up the flag at the center of map.
6. Check the console logs, look at player and flag for conclusion.

**Comment by 111112oo** [comment]
This is a fix I would greatly appreciate, any way I try to target the flag holder always ends up with some downside I can't fix.

**Comment by worMatty** [comment]
I wanted to make a custom game mode where players could carry something akin to a 'hot potato'. The longer they held onto the flag, the more damage they would take. The problem was I couldn't target the activator because, bizarrely, the flag was sending its own entity index as the !activator. The alternative was to parent a trigger_hurt to the flag but that ran the risk of affecting nearby players. I could also use it as a kind of access control where a player can only move to an area if they're carrying a flag. 

I'd really love the ability to use **!caller** to target the flag itself, too. I had an idea to use the health of the flag as a sort of battery charge level but there was no way to send the input to it without giving it a targetname, and I was going to have multiple flags in play at once.

**Comment by agrastiOs** [comment]
@kisak-valve Requested functionality added on latest patch.

**Comment by kisak-valve** [comment]
Per "Added new item_teamflag ouputs OnPickup1, OnDrop1, and OnCapture1 that fire outputs with the player as the activator" in the [2021-11-15](https://www.teamfortress.com/post.php?id=101361) TF2 update, please retest.

**Comment by IzotopeDev** [comment]
This is greatly appreciated!

**Comment by St-Relock** [comment]
I've retested this issue.

According to my tests, it works well, here's a [short video](https://youtu.be/C9JJm8mZcD4).
What I did is just changed outputs and also added `OnCapture1` output for all outputs to test.
[Map's gist](https://gist.github.com/St-Relock/ca76f8aa57454806892a6f3553258561) I was using for retest, You can check this out.

Big thanks from me and community! This is the very useful fix!
**Mappers *really* appreciate what You did...**

**Comment by agrastiOs** [comment]
@kisak-valve I've also retested - using the new outputs makes the scenario OP mentioned work. This is fixed.

**Comment by St-Relock** [comment]
Could i mention [this issue](https://github.com/ValveSoftware/Source-1-Games/issues/3681) please?

You guys, who is interested, check this out. It's also related with the map logic and easy to fix.
If you find it interesting, put a thumb up or something like this, *please*.
I make a tutorial about it, if it's released.

*Sorry for a bit mess...*
It's just gathered some mappers around, so it would be a sin not to mention it, thought it's close topic.

**Comment by agrastiOs** [comment]
@SpookyToad2 fixed
