### ISSUE TITLE
[L4D1] Specific sprays causing servers to crash

### ISSUE THREAD

**Issue by Diggingwolf2605** [ValveSoftware/Source-1-Games#3817]
Players can use specific sprays to cause servers to crash by either invalid formats or specific sprays to cause server lag/crashes.

**Comment by kisak-valve** [comment]
Hello @Diggingwolf2605, this issue is already being tracked at #3249. Closing as a duplicate.

**Comment by AshThe9thSurvivor** [comment]
What's the point of deleting this post saying it's a duplicate, if they're not going to fix it?

**Comment by Diggingwolf2605** [comment]
@kisak-valve There is no reason why this needs to be closed. Most exploits have existed for several years that have been left unpatched to only be exploited by several players. Please take responsibility and patch these to prevent such abuse from happening. The issue you had mentioned was posted back in 2020 which has still not been fixed.

**Comment by AshThe9thSurvivor** [comment]
> @kisak-valve There is no reason why this needs to be closed. Most exploits have existed for several years that have been left unpatched to only be exploited by several players. Please take responsibility and patch these to prevent such abuse from happening. The issue you had mentioned was posted back in 2020 which has still not been fixed.

There is nothing to wait for, they don't care about anything, they say they don't want to update the game because they don't want to touch the code, I being just a player made an unofficial update for the game with some friends, and I didn't mess up the code, in fact I didn't even touch it, they were all superficial changes, we added new maps, new common infected, events that don't exist in L4D1, improvements to some models, texture corrections, a new and updated main menu, and more, much more, and they who they are more experts they can not modify the game?, it is the dumbest excuse I have ever heard.

**Comment by kisak-valve** [comment]
Hello @AshThe9thSurvivor, friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a Source engine developer myself. There's no value in fragmenting the discussion of an issue over multiple issue reports, which is why duplicate issue reports get closed.

**Comment by AshThe9thSurvivor** [comment]
> Hello @AshThe9thSurvivor, friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a Source engine developer myself. There's no value in fragmenting the discussion of an issue over multiple issue reports, which is why duplicate issue reports get closed.

Thank you very much for your information, but I suppose that you are in charge of filtering which errors are corrected and which are not, I just hope you listen to us.
