### ISSUE TITLE
No More Room In Hell: Game lockup when servers change maps.

### ISSUE THREAD

**Issue by Git-Forked** [ValveSoftware/Source-1-Games#3855]
#### System information: 

steam.sh[9739]: Running Steam on manjarolinux 21.2.3 64-bit
steam.sh[9739]: STEAM_RUNTIME is enabled automatically
setup.sh[9812]: Steam runtime environment up-to-date!
steam.sh[9739]: Steam client's requirements are satisfied

#### Steps to reproduce: 

1. Server changes maps.
2. Game freezes. 

#### Notes: 
Not specific to only Manjaro or Arch Linux.

**Comment by kisak-valve** [comment]
Your previous issue at #3854 **might** have been triggered by some change on Valve's side, which is why I left it alone. This is reads as something entirely game-specific and since this is a third party game, it needs to be evaluated by the game's devs.

Closing as out-of-scope for this issue tracker.
