### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by AzureAzel** [ValveSoftware/Source-1-Games#3901]
Deleted

**Comment by xxmyn** [comment]
no

**Comment by Pinsplash** [comment]
of course the only opposition has activity on cheat repos

**Comment by xxmyn** [comment]
> of course the only opposition has activity on cheat repos

Cathook doesn't run bots using textmode, public knowledge, removing textmode is useless and valve already made it so textmode players can't join most servers or get item drops, textmode "players" are just afk bots that people use to farm stranges in strange farming servers.

**Comment by Col-E** [comment]
> valve already made it so textmode players can't join most servers 

This check is built into the client, not the server. Thus you can just patch out the check locally and the server has no way of knowing you're running headless. In fact, this is actually what cathook does. You can verify by looking at `/src/textmode.cpp` in their repo.

You can remove the `-textmode` flag but if the feature still exists in the engine bot authors can still use it. It just requires a bit of extra effort to invoke the functions that are no longer directly exposed as a command line flag since now its on the bot logic to do so. 

That being said, there are quite a few ways to detect bots from the server's side of things. Bots can identify other bots, its been a feature in a few cheats for quite a while. Consider the requirements to support such a feature.

**Comment by wgetJane** [comment]
we can stop cheaters once and for all by adding an `-imcheating` launch option, which bans the player when they launch the game

**Comment by Ashetf2** [comment]
@AzureAzel I don't want to bother you but why closing this?

**Comment by StarterX4** [comment]
Just block players running textmode from casual matches, but don't block from community servers.

**Comment by Ashetf2** [comment]
> Just block players running textmode from casual matches, but don't block from community servers.

I think that's actually what happens, but you know, cheaters find a way
