### ISSUE TITLE
[TF2] Arena Mode HUD conflicts with Team Status HUD (quick team status bar)

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#3967]
The quick team status bar conflicts with the older Arena Mode HUD. A quick fix would be to have the game hide the Arena HUD if tf_use_match_hud is set to 1.
![image](https://user-images.githubusercontent.com/108029512/175787480-7e0309f3-9076-4ae7-98ae-dd8e15f28491.png)

**Comment by 111112oo** [comment]
I mostly play arena mode based gamemodes, and this has always bothered me. Hiding the Arena HUD as suggested in OP would not be a good solution as seeing the alive players is very helpful.

**Comment by Ashetf2** [comment]
Just change x and y values in HudArenaPlayerCount.res

```
	"blueteam"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"blueteam"
		"xpos"			"c-55"
```
from
```
{
	"blueteam"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"blueteam"
		"xpos"			"c-30"
```
and
```
	"redteam"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"redteam"
		"xpos"			"c-5"
		"ypos"			"0"
```
from
```
	"redteam"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"redteam"
		"xpos"			"c-30"
		"ypos"			"21"
```

**Comment by kisak-valve** [comment]
[TF2] Community Fix for the Arena Player Count HUD

Issue transferred from https://github.com/ValveSoftware/Source-1-Games/issues/5243.
@GrassyTrams posted on 2023-10-12T06:27:48:

Arena Mode has had an unusable player count UI since 2016, the linked steam workshop community fix can fix this issue.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/120645510/268e943e-6025-4aee-8bb4-bacfcff1755e)
[Steam Workshop Link](https://steamcommunity.com/sharedfiles/filedetails/?id=3049413665)

**Comment by kisak-valve** [comment]
Hello, per "Fixed Arena mode player count HUD layout problem (community fix from Funicular)" in the [2023-10-27](https://www.teamfortress.com/post.php?id=211509) Team Fortress 2 update, please retest this issue.

**Comment by Kruphixx** [comment]
> Hello, per "Fixed Arena mode player count HUD layout problem (community fix from Funicular)" in the [2023-10-27](https://www.teamfortress.com/post.php?id=211509) Team Fortress 2 update, please retest this issue.
![Screenshot 2023-10-28 145921](https://github.com/ValveSoftware/Source-1-Games/assets/50501742/a06dbdd0-3b8b-4d25-9df3-8f7e1cfed8b1)

Can confirm this is fixed now.

**Comment by kisak-valve** [comment]
Closing as fixed.
