### ISSUE TITLE
nullyuki fuck off

### ISSUE THREAD

**Issue by TKW905** [ValveSoftware/Source-1-Games#3986]

**Comment by TF2CutContentWiki** [comment]
_set the max edicts to as high of a value as the game can handle_ 😉🤫

**Comment by DosMike** [comment]
IDK why people always bring up cosmetics or plugins with that when the stock game itself has always run the risk of crashing. Shounic made a great video on that once <https://www.youtube.com/watch?v=O0QfINYF8CE>.
The players w/o map could get up to ~900 edicts, leaving ~1150 edicts for maps and plugins. The maps range from <200 to 1585 with (ref video), exceeding the limit.
Even if this risk is lowered by using vscripts for map logic, I'd still love to see more edicts for crazy gameplay plugins tho :)

**Comment by ThatCanadianEh** [comment]
> IDK why people always bring up cosmetics or plugins with that when the stock game itself has always run the risk of crashing. Shounic made a great video on that once https://www.youtube.com/watch?v=O0QfINYF8CE. The players w/o map could get up to ~900 edicts, leaving ~1150 edicts for maps and plugins. The maps range from <200 to 1585 (ref video), exceeding the limit. Even if this risk is lowered by using vscripts for map logic, I'd still love to see more edicts for crazy gameplay plugins tho :)

I mentioned the wearables thing mainly because I had worked with Creators.tf where we encountered the issue of the wearables array being too small to support custom wearables without losing official wearables due to exceeding that array size.

The edicts count, I should've been more specific in mentioning stuff like shounic's video because what you said is true. That edict limit is way too small. It was fine for 2007 but it has needed to be increased for quite some time now. I'm surprised it hasn't yet been increased.

**Comment by Guitarsmasher** [comment]
I think this is especially a more important issue now that the player count for servers can go up to 100 players, I agree with increasing the max edict limit count.

**Comment by Synkstar** [comment]
Increase it to 8k like gmod

**Comment by Guitarsmasher** [comment]
> Increase it to 8k like gmod

Honestly I think even Gmod has problems with hitting the edict limit too frequently and they already have a "high" edict limit for source 1 standards. So I would say TF2's max edict count should be a good amount higher than even Gmod.

**Comment by Synkstar** [comment]
> > Increase it to 8k like gmod
> 
> Honestly I think even Gmod has problems with hitting the edict limit too frequently and they already have a "high" edict limit for source 1 standards. So I would say TF2's max edict count should be a good amount higher than even Gmod.
> 
> 

Gmod is a sandbox game and tf2 is not. The edict count on gmod is fine. If tf2 had even twice as many it would probably be ok too.

**Comment by stevefan1999-personal** [comment]
But what about the [3GB Barrier](https://en.wikipedia.org/wiki/3_GB_barrier?wprov=sfla1)? 

Since edicts are basically transactional memory snapshots synchronized on every tick for networked game, this means the memory requirement will scale monotonically as well.

And worst of all, TF2 is a 32-bit game, so recklessly raising the edicts limit would quickly bork the memory allocation limit and still be a fatal error anyway. 

Unless TF2 implements [PAE](https://en.wikipedia.org/wiki/Physical_Address_Extension?wprov=sfla1) and multithreaded processing, I object to the change. Raising edict limits is simply useless and futile due to other relevant factors.

I don't think an official 64-bit or Source 2 port of TF2 is ever possible? Although the last time I checked the leaked source code, I was able to reproduce some game source components in 64-bit. Netcode compatibility not sure, but sourcemod would be sure dead.

What was not available to upgrade to 64-bits are the library files. Those are probably licensed, close sourced and probably don't have 64-bit artifacts at that time, which means if we can get those sorted out...
