### ISSUE TITLE
[TF2] bugged animations while using the contracker exploit

### ISSUE THREAD

**Issue by Platina6978** [ValveSoftware/Source-1-Games#4065]
Despite being quite a popular exploit, I myself don't know how it works and couldn't find any open issues about it on here either. Opening this ticket so that someone who understands the exploit better and knows how to reproduce it can help out, and so it would get noticed and hopefully fixed!
As far as I'm aware, a bug involving the contracker allows players to move, attack,.... freely despite only showing the animation of having the contracker equipped. This is an obvious oversight and it's quite clear how this can be/gets abused to gain an unfair advantage in the game.
Apologies if this is a dupe of another issue.

**Comment by slender100** [comment]
> Despite being quite a popular exploit, I myself don't know how it works and couldn't find any open issues about it on here either. Opening this ticket so that someone who understands the exploit better and knows how to reproduce it can help out, and so it would get noticed and hopefully fixed! As far as I'm aware, a bug involving the contracker allows players to move, attack,.... freely despite only showing the animation of having the contracker equipped. This is an obvious oversight and it's quite clear how this can be/gets abused to gain an unfair advantage in the game. Apologies if this is a dupe of another issue.

https://www.youtube.com/watch?v=7rV2Qms1bpU, 0:26-1:19

**Comment by AzureAzel** [comment]
This typically occurs through starting the Contracker animation, and then having the animation get interrupted before it can end itself. This can be done through taunting before the ending animation plays, or by switching loadout presets to another loadout that does not have the Contracker equipped before the ending animation plays, due to the fact that the animation will only play if the Contracker item is equipped in the action slot. (You don't need to have the actual loadout itself change, just changing the preset outside of spawn is enough for it to happen.)

**Comment by FindTheBorealis** [comment]
Needs retesting as per "Fixed an exploit related to the ConTracker and being able to move/shoot while it's deployed" in the recent summer update.

**Comment by kisak-valve** [comment]
Closing per the last comment.
