### ISSUE TITLE
[TF2] Short Circuit collides with but doesn't impact on some doors

### ISSUE THREAD

**Issue by slender100** [ValveSoftware/Source-1-Games#4066]
Video demonstration: https://www.youtube.com/watch?v=ks_p_bN3Kck

If used in conjunction with #2738 this can damage players near the gate during setup time, but there aren't really any other use cases with this that can make the game unplayable.

This is the same exact bug as [this one](https://www.youtube.com/watch?v=jNxffe3FuN8) fixed back in 2016, seems like this wasn't fixed for the new short circuit projectile.

**Comment by kisak-valve** [comment]
Hello @slender100, I'm not seeing how this differs from the referenced issue report, but since this adds a bit more insight, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/2738#issuecomment-1186631068.

Closing in favor of the older issue report.
