### ISSUE TITLE
[HLDM:S][SDK} Model browser GUI show folders only

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#4248]
World model browser show folders only
![Model_browser](https://user-images.githubusercontent.com/5712715/188338722-8a199c56-7403-446e-9ce2-dc81a4344ec2.png)

**Comment by kisak-valve** [comment]
Hello @1157, as far as I can tell, this is the same SDK tool issue which I've transferred to https://github.com/ValveSoftware/source-sdk-2013/issues/555.

If I've transferred that issue report in error, then explain why you think that action was wrong so that I can understand and be more consistent in the future. I doubt that this quirk is specific to the hammer editor of a single game.

Closing as a duplicate.

**Comment by 1157** [comment]
This is ok i just seen it deleted and not closed. They just made a new Model browser so it might explain some bugs.
https://developer.valvesoftware.com/wiki/Hammer_What%27s_New
