### ISSUE TITLE
[TF2] Add feature to toggle conscientious objector signs in-game

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4249]
I've heard this one passed around many times before, but personally I think there should be an option to disable the images on the objectors. Because of the fact that it's decalable, so many people decide to put images on it that are NSFW or otherwise. I've heard that YouTube could potentially demonetize or age restrict a TF2 video if a sign with a certain image is shown on screen. This could be blurred or edited out, but Twitch has no such feature and thus is much harder to avoid. If sprays can be disabled in the options menu, so should objectors.

**Comment by Ashetf2** [comment]
Don't forget about the Clan Pride, the Flair!, etc, so you are asking for disabling decals in general. I suggest to add options to not hide decals from friends.

**Comment by kisak-valve** [comment]
[TF2] [Feature Request] ConVar for disabling custom decals

Issue transferred from https://github.com/ValveSoftware/Source-1-Games/issues/4921.
@DudeTheNinja posted on 2023-04-24T19:49:05:

Hi,

Whilst it is the case that player sprays can be disabled, custom item images (i.e. decals as seen on the Conscientious Objector, Photo Badge, Flair! and the Clan Pride items) are still permanently enabled. This is a problem because the custom decal feature is still used (and abused) by many to display decals that violate the rules of the Steam Subscriber License Agreement, if not straight up illegal imagery in rare cases.

If Valve is not going to moderate the custom images despite claiming to when applying a Decal Tool to an item, at least let us 

Thus, I propose the following feature: a convar/option, both server- and client-side, to disable them. Valve servers could have the server set the command to 0, and have the client command set to 0 by default (set to 1 in the Multiplayer > Advanced settings, like with sprays)

I have written changes to `client/econ/tool_items/custom_texture_cache.cpp` (based on outdated leaked code, so the exact line positions may have changed in due time) that illustrate a real simple implementation of a solution.

```c
// Add to header inclusions:

#include "convar.h"

// Insert at line 26:

// Allows for control over custom decals
ConVar cl_allow_custom_decals( "cl_allow_custom_decals", "0", FCVAR_ARCHIVE, "Opt-in to view custom images on decalable items", true, 0, true, 1 );
ConVar sv_enable_custom_decals( "sv_enable_custom_decals", "0", FCVAR_REPLICATED, "Allow custom images on decalable items. Clients must also set cl_allow_custom_decals to 1.", true, 0, true, 1 );

// Replace lines 782 to 785:

\tif ( texture && cl_allow_custom_decals.getInt() == 1 && sv_enable_custom_decals.getInt() == 1 ) // Check if both server enables decals and player opts in
\t{
\t\tm_pBaseTextureVar->SetTextureValue( texture );
\t\t
\t}
```

**Comment by DudeTheNinja** [comment]
I have since uploaded my proposal (with the code snippets) to the Steam Workshop as per recommendation by other fix contributors:

https://steamcommunity.com/sharedfiles/filedetails/?id=2967135505

**Comment by Ashetf2** [comment]
The submission above is now private. Valve can still view it though.

**Comment by DiarrheaMcgee** [comment]
please add this

**Comment by DiarrheaMcgee** [comment]
i just went over a list of around 100 players and 8 of them had explicit content on their conscientious objectors.

one of them just had about 10 nude anime pictures https://backpack.tf/profiles/76561198068646856

**Comment by DudeTheNinja** [comment]
[Most recent update ](https://www.teamfortress.com/post.php?id=223066)adds this.

Should be closed now.

**Comment by Ashetf2** [comment]
![imagen](https://github.com/user-attachments/assets/e2658cb4-a120-4902-ac40-ed017c12a5e2)

**Comment by kisak-valve** [comment]
Closing as implemented.
