### ISSUE TITLE
[L4D2 Feature Suggestion] Splitscreen Menu

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/Source-1-Games#430]
It'd be nice if there was a menu to pick creating a splitscreen game, like Portal 2 now has. So you could use two controllers or a keyboard/mouse controller combination if possible.

**Comment by ThisNekoGuy** [comment]
@kisak-valve @d10sfan 
Is there a reason why this was closed? Because I haven't seen this feature implemented in the PC version, myself.

**Comment by d10sfan** [comment]
> @kisak-valve @d10sfan Is there a reason why this was closed? Because I haven't seen this feature implemented in the PC version, myself.

Mainly the ticket was 10 years old, with no interest at all.

**Comment by ThisNekoGuy** [comment]
To be fair, those most interested in this likely:

- Don't know this repo exists
- Don't expect this to be done at all (because of online gaming)
- Are more likely to find the jank modded "solution" to this on the Workshop than come this far to voice a desire for it

Personally, I can say that, if it did support splitscreen, I'd have one more reason to play it on an external display via the Steam Deck with family when I go out (I'd also use it at home though) but the expectation this would but the expectation this will be done is so low (due to this being a less serious issue than other problems like the game running out of RAM so easily on anything but the absolute lowest settings in my own experience - making Workshop support, itself, a footgun even if the end-user is actually careful) that it's hard to really bother vocalizing this. After 11 years (since this issue was posted), I think most people (unfortunately) just accept the fact that L4D2 isn't going to get updated beyond niche engine bugfixes and security exploits (the unexpected Last Stand update aside, of course).

Not that there's much more to say about the issue to begin with anyway; everyone knows it doesn't have support for it, and if everyone who did want it came here to say so it wouldn't really add anything to the discussion besides the obvious: communicating the same thing OP said.

**Comment by Dragon-Mom** [comment]
Strongly desire this, especially as the Steam Machine is coming soon. Honestly should have been a feature at launch on PC.
