### ISSUE TITLE
[TF2] [Feature Request] Weapon Improvements

### ISSUE THREAD

**Issue by Arbitz** [ValveSoftware/Source-1-Games#4327]
The last change to weapon stats (as far as I know) was the 2020 Blue Moon update. Since then, we haven't had any balance patches despite several weapons being dreadful to use. The Sandman, Baby Face Blaster, syringe guns and Righteous Bison are the main offenders.

Attached is a text file with some proposals and ideas, most of these not needing that much coding and mainly relying on various number values being changed/traits being added. (Based on my hobbyist understanding of coding).

[BALANCE.txt](https://github.com/ValveSoftware/Source-1-Games/files/9675316/BALANCE.txt)

**Comment by kisak-valve** [comment]
Hello @Arbitz, in general, multi-issue issue reports are bad for any issue tracker, and this is both that and obfuscated in an attachment to make it difficult to search for in detail. Instead of one untrackable feature request stating that weapon balance overall should be changed, please make a separate feature request to adjust each individual weapon and explain exactly why you think that change needs to happen.
