### ISSUE TITLE
no

### ISSUE THREAD

**Issue by TKW905** [ValveSoftware/Source-1-Games#4358]

**Comment by MikhailaTF** [comment]
I think the panic attack should be the only item having this issue. Any other weapons in the game that are shared between classes still occupy the same slot (for example the pistol uses the secondary slot for both scout and engineer and the frying pan uses the melee slot on every class)
The only exception I can think of is the stock shotgun, which obviously cannot be crafted anyway.

**Comment by TF2CutContentWiki** [comment]
> I think the panic attack should be the only item having this issue. Any other weapons in the game that are shared between classes still occupy the same slot (for example the pistol uses the secondary slot for both scout and engineer and the frying pan uses the melee slot on every class) The only exception I can think of is the stock shotgun, which obviously cannot be crafted anyway.

Yeah, I didn't find any other instances of this type of issue. I think it's just due to the PA being multi-class in a weird way where it is counted as both a Primary and a Secondary while being shared among 4 classes.

Just kind of a pain trying to go for a primary Pyro craft to get a Nostromo Napalmer for example, and getting a Panic Attack.
