### ISSUE TITLE
[TF2] Client crashing with Ghoulpit contract activated

### ISSUE THREAD

**Issue by Gamecube762** [ValveSoftware/Source-1-Games#4379]
After the 10/7/22 update, TF2 crashes when loading into any map if the Ghoulpit contract activated. Deactivating Ghoulpit seems to be the workaround. Activating Ghoulpit while already in a map will still cause the same crash.

Here's a crashdump of the issue: [crash_hl2.exe_20221007212518_1.dmp.zip](https://github.com/ValveSoftware/Source-1-Games/files/9738570/crash_hl2.exe_20221007212518_1.dmp.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is an EXCEPTION_ACCESS_VIOLATION_READ in client.dll.

**Comment by agrastiOs** [comment]
Can confirm that at least 2 players have reported this issue.

**Comment by gunboy001** [comment]
Can confirm it also happens on the linux build

**Comment by kaustubhowmick** [comment]
Can confirm it is happening to my game. I reinstalled Steam and TF2, but even that didn't fixed it.

**Comment by Wosheereal** [comment]
This also occurs on Spookeyridge as well.

**Comment by santumerino** [comment]
Can confirm it's happened to me too.

**Comment by brokenphilip** [comment]
After experiencing this crash myself, I can confirm the exception address of the attached dump matches mine (client+0x00323520) after the reproduced steps. Seems like the function in question at that address is related to starting/tracking the contract itself.

Interesting to note what the contract looks like:
![image](https://user-images.githubusercontent.com/13336890/194968979-f7be3c42-8c8b-4f51-a86d-f63ac62653a6.png)
Note the "2/2 Dominate a player as Pyro" bonus quest, not only is it complete despite me never playing the map, but also the star is still greyed out, not to mention the quest itself goes outside the usual theme of Scream Fortress contracts, suspecting me to believe that this was definitely not intentional.

**Comment by nosoop** [comment]
Fairly sure Gamecube762 forwarded this information to the appropriate people, but from what I could gather it crashes on `__MsgFunc_QuestObjectiveCompleted`.

It looks like the update between game versions 7565522 and 7570091 also removed the objective "Kill with a pumpkin bomb on Ghoulpit" (protodefindex 7055), which seems to line up with the contract displaying invalid quests.

**Comment by kisak-valve** [comment]
Hello, per "Fixed a client crash related to the Ghoulpit contract" in the [2022-10-11](https://www.teamfortress.com/post.php?id=144283) Team Fortress 2 update, please retest this issue.

**Comment by brokenphilip** [comment]
After retesting, the game doesn't crash anymore, and the bonus objective is working as intended:
![image](https://user-images.githubusercontent.com/13336890/195166020-4524ecae-a333-4272-a414-9c2da9dff9ca.png)

**Comment by Gamecube762** [comment]
This is fixed. The contract is both working and no longer crashing.
