### ISSUE TITLE
[TF2] Head Hedge Unusual Effect Upside-down/Backwards

### ISSUE THREAD

**Issue by leo-proct** [ValveSoftware/Source-1-Games#4390]
Several users including myself have an issue where the effect is upside down or backwards depending on the effect.

Adjusting unusual doesn't seem to fix the issue.

![image](https://user-images.githubusercontent.com/25711330/194930100-62bb6896-908e-44b6-9800-54fed63add58.png)
![image](https://user-images.githubusercontent.com/25711330/194930182-551762d9-554a-476f-997a-1fce9ecd839d.png)
![image](https://user-images.githubusercontent.com/25711330/194930209-e3e49f3d-cd16-452c-942c-5681c2e13d3c.png)

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed some unusual effects using the wrong orientation for The Head Hedge 

This needs to be retested.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Camden66** [comment]
This bug seems to still be affecting the "**Demonic Impaler**" effect on the Head Hedge.
When equipped the effect is upside down.
When "**Adjust Unusual**" is checked, the effect is right side up, **but** **crooked** 
(As seen in second screenshot)

<img width="1694" height="818" alt="Image" src="https://github.com/user-attachments/assets/a90002bc-df29-4157-91a7-9cb1f1f422d6" />

<img width="1475" height="797" alt="Image" src="https://github.com/user-attachments/assets/ce7f38b3-aa33-4fa1-9b9f-56edbc029f80" />
