### ISSUE TITLE
Inscription "Next 12" does not display correctly in different languages

### ISSUE THREAD

**Issue by Multinic** [ValveSoftware/Source-1-Games#4427]
Normal (English)
![Normal](https://user-images.githubusercontent.com/109987396/197205537-76225c71-c022-4b42-96ed-cc33f0d31180.png)

Bug (Other languages)
![Bugget](https://user-images.githubusercontent.com/109987396/197205930-b77ea468-df11-4538-a41a-f0d9038a3bc4.png)

**Comment by mbsg** [comment]
I believe this happens because in "replay_russian_txt" (Team Fortress 2 > hl2 > resource), "%S1" is being used instead of "%s1". This is the same case with other languages, not all.

![Screenshot](https://user-images.githubusercontent.com/113659515/197431746-e6ac0681-c3cf-48b9-ade8-557b5cce9086.PNG)

**Comment by mgptd** [comment]
This was fixed in the November 4, 2022 Patch for TF2 (All "%S1" were replaced with "%s1")

**Comment by kisak-valve** [comment]
Closing per the last comment.
