### ISSUE TITLE
[TF2] Small ammo packs give more ammo/metal on Windows-hosted servers

### ISSUE THREAD

**Issue by okamiterasu** [ValveSoftware/Source-1-Games#4522]
When playing on a server hosted on a Windows system, small ammo packs will often give players one more ammo or metal than on a Linux or Valve server

Windows:
![image](https://user-images.githubusercontent.com/6588251/202832564-36be9afc-d482-4dc3-a9a1-1cc90cf98a60.png)
![image](https://user-images.githubusercontent.com/6588251/202832461-722a31a0-6cc2-4a7c-8d10-7310f1d0f2b7.png)

Linux:
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/6588251/202832803-59fc66ac-60b2-4bb6-9e25-43e4a97fc2e9.jpg)
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/6588251/202832793-ed5524f5-6644-4642-9507-fc181da32f40.jpg)

**Comment by Doclic** [comment]
[shounic already made a video about this](https://www.youtube.com/watch?v=QzZoo1yAQag)
The problem is that the code multiplies the max ammo/metal by 0.2 when you pickup the ammo pack.
The Linux compiler thinks that the result is 40, so it works fine.
The Windows compiler thinks that the result is a bit more than 40, which shouldn't cause a problem, but the code uses a ceil function instead of round to nearest, so 40 and a bit becomes 41.
The fix is just making this function use a round to nearest function.

**Comment by okamiterasu** [comment]
Fixed. Presumably during the x64 update
