### ISSUE TITLE
[L4D1/L4D2] Missing snd_mute_losefocus console variable

### ISSUE THREAD

**Issue by Withaust** [ValveSoftware/Source-1-Games#4600]
I don't know why this command has been removed, it exists in CSS and CSGO, so it makes little sense for it to be removed in L4D1/L4D2.

**Comment by Diggingwolf2605** [comment]
@kisak-valve 

L4D1 needs to have a label on this github area since it is a Valve title.

@Withaust

I'm not familiar with the snd_mute_losefocus command, but there are also a few other commands that have been removed such as the sv_vote commands missing entirely in L4D1 Servers.

sv_vote_creation_timer
sv_vote_duration_timer
