### ISSUE TITLE
[TF2] [Feature Request] Revert changes done to the "True Scotsman's Call" community-contributed taunt (added as "Bad Pipes" to the game)

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#4756]
https://steamcommunity.com/sharedfiles/filedetails/?id=517954905

https://youtu.be/bLhYrIHsW94

I can't stress enough how bad this taunt sounds as it is currently in the game.

In my point of view, there was no reason for the Team Fortress 2 development team to degrade the quality of this taunt.

It would have been much better with the original audio implemented in the game.

There were 2 instrument-related taunts released before the "Bad Pipes" taunt that didn't get their sounds ruined. In order of release date: [Shred Alert](https://wiki.teamfortress.com/wiki/Shred_Alert) for all classes and [Killer Solo](https://wiki.teamfortress.com/wiki/Killer_Solo) for the Sniper.

There were also 6 instrument-related taunts released **after** the "Bad Pipes" taunt that didn't get their sounds ruined. In order of release date: [Fubar Fanfare](https://wiki.teamfortress.com/wiki/Fubar_Fanfare) for the Soldier, [Didgeridrongo](https://wiki.teamfortress.com/wiki/Didgeridrongo) for the Sniper, [Dueling Banjo](https://wiki.teamfortress.com/wiki/Dueling_Banjo) for the Engineer, [Runner's Rhythm](https://wiki.teamfortress.com/wiki/Runner%27s_Rhythm) for the Scout, [Surgeon's Squeezebox](https://wiki.teamfortress.com/wiki/Surgeon%27s_Squeezebox) for the Medic and [Scorcher's Solo](https://wiki.teamfortress.com/wiki/Scorcher%27s_Solo) for the Pyro.

We had two instrument-related taunts before, and **six after**. Why did the "Bad Pipes" taunt have to be ruined?

I believe most people would agree with me on this matter.

**Comment by Ashetf2** [comment]
Define "ruined"

**Comment by JoriKos** [comment]
I don't think this is ruined, it makes more sense for Demo to play the current song instead. I find the original song to be very overwhelming and won't really fit the taunt well. Plus it's more amusing that he plays so badly and then compliments himself.

**Comment by SomeBloodyMinger** [comment]
> I don't think this is ruined, it makes more sense for Demo to play the current song instead. I find the original song to be very overwhelming and won't really fit the taunt well. Plus it's more amusing that he plays so badly and then compliments himself.

If the Demoman can canonically go on slaughtering sprees while drunk with extreme precision, then I'd be inclined he could do anything drunk. But just my two cents, I do agree the OG-audio bagpipes sounded better.

**Comment by JoriKos** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/4756#issuecomment-1429072426

You can make the character shine through voice lines/taunts, adding a permanent drunk effect to Demoman when playing him because he's canonically drunk would make it awful.

**Comment by gabrielwoj** [comment]
Some people may have bought this taunt because of the wacky sounds. The developers can't simply change something that people have bought with real money. Maximum that they can do is add the old original song as a "style", although, there hasn't been any taunts with "styles" so far (the Spent Well Spirits taunt once had a way to change styles from the store, but it didn't do anything, and from the taunt menu, you couldn't change styles).

**Comment by gabrielwoj** [comment]
> > The developers can't simply change something that people have bought with real money (that is not tied to gameplay balance).
> 
> https://blog.counter-strike.net/index.php/2023/02/41124/
> 
> > [REVOLUTION CASE]
> > – The AWP | Doodle Lore has been replaced by the AWP | Duality in the Revolution Case
> > – Existing AWP | Doodle Lore inventory items have been converted to the AWP | Duality

In the example you have linked, it seems the problem was because the textures had stolen artwork on it (or by the words of the accused workshop creator for the AWP skin, too heavily inspired, though I'm not here to pick what side, and who's right or who's wrong, just explaining what happened).

This, however, does not apply for this taunt as the sound effects were most likely made by Valve themselves, while the animation and props were made by the original Workshop people. If this was to be applied here, let's say, the prop was stolen (either model or textures, or both), or the animation was stolen from somewhere else, these would most likely be remade and reanimated, but the sound would still be the same, as it's most likely came from Valve.

The only way this could be applied in the same way that the CS:GO Patch did, is that, someone at Valve stole the sound effects from somewhere else, or if Valve asked the Workshop creators for the taunt to make the sounds, and someone from the team stole it, which I don't think it happened. There are a lot of "if-s" here, so I can't really associate these two things. Yes, it was a case of something being changed after others have purchased, but there was a much different reason behind it.
