### ISSUE TITLE
[TF2] [MvM] Buyback exploit lead to infinite money

### ISSUE THREAD

**Issue by KalleKokosnott** [ValveSoftware/Source-1-Games#4790]
During any pre-wave in MvM, when a player has to choose a class, the player can execute "td_buyback". This will force a buyback, but can't respawn the player, since they have not chosen a class yet. 

For some reason, the buyback value is negative, and will continuously grow in a decremental rate of 5 credits for every second that passes. This means that the exploit becomes more valuable to exploiters as the time passes by, due to the fact that players will earn more and more credits from this. I believe this negative buyback time is connected to the time spent on the map, though not connected to the players' connection times. There is no cooldown for this kind of buyback, and can be spammed several times a second, and can be deafening. This means that it is not just a gameplay advantage, but also a griefing tool for malicious players, as it is quite loud in quantity, and it spams the text chat.

Steps for reproduction:
1. Join a Mann vs. Machine server.
2. Click through info panels, until class menu shows up.
3. Do not choose a class, but open the developer console (press ESC).
4. Execute the command "td_buyback". You should hear the buyback sound, charged for a negative value, and have received credits.
Speculation: Dependent on how long the server has been on the map, the greater the negative value will be.

With such an exploit, it is then possible to max out upgrades at the very first wave of any mission. As I stated before, this is possible during **any** pre-wave, where you merely reconnect with the "retry" command to get to the class menu again, in order to execute the "td_buyback" command again for more credits.

**Comment by jh34ghu43gu** [comment]
iRespawnWait time probably goes negative in class selection which makes the iCost negative (I'm guessing it has something to do with the GetNextRespawnWave function during in-between waves but probably don't need to worry too much about the exact specific).

Should be a simple fix to put a <0 check on iCost for the td_buyback command in the tf_player.cpp ClientCommand function?

Probably also needs a similar check in tf_spectatorgui.cpp in the UpdateReinforcements method under the if(bBuyBackVisible) statement so costs aren't incorrectly displayed negative.


It would also be nice if it checks for the player being in the class selection screen since people would still be able to spam buybacks in the normal game even if they are limited to mission money. It already checks for freezecam and deathcam, not sure what camera mode a class selecting player is in.



Or shake up the meta game and introduce that [buyback credit system](https://www.youtube.com/watch?v=c4tyFa_oxag) that never got turned on :)

**Comment by rowedahelicon** [comment]
Could also add a check to see if the player using the command is a valid class. I wrote a temp fix for server owners here. https://github.com/rowedahelicon/MvM-Cash-Exploit-Fix

**Comment by CopCorvette** [comment]
Now theres people trolling or bots idk spamming this in spectator ruining games... credits to Delfy for ruining MvM

**Comment by jouva** [comment]
> Could also add a check to see if the player using the command is a valid class.

This is probably better than the `iCost` check, because this command is still able to be ran during a wave, but does not yield the credits to the player. It does, however, spam the message log and allow the player to spam an extremely loud sound over and over as a result to the cost of 0-5 credits.

**Comment by jh34ghu43gu** [comment]
> It does, however, spam the message log and allow the player to spam an extremely loud sound over and over as a result to the cost of 0-5 credits.

Both checks would probably be good to have, the original reply I put was just a quick look to see where the bug probably occurs in the hopes we could get a hot fix before the weekend. I was aware of the "drums" exploit but since only <5 people really use that I didn't see the significance of that. 

There is also another exploit that scouts can do to do negative buybacks. Negative credit check would fix that one.

**Comment by jouva** [comment]
> There is also another exploit that scouts can do to do negative buybacks. Negative credit check would fix that one.

That's also fair because no matter what, negative buybacks don't make sense, so if any other exploit allows for that, this'll be another gate in the way.

**Comment by ReplayCoding** [comment]
The reason the bug occurs is because flWaveTime is 0 during class selection. As a result, iRespawnWait will end up being equal to `-gpGlobals->curtime`, which will take a negative amount of credits from the player (giving them credits). Replacing `if ( GetCurrency() >= iCost )` with `if ( iCost >= 0 && GetCurrency() >= iCost )` will fix this bug, and it won't spam the game sound and chat. There isn't any reason to have any other checks, as this should catch everything.

**Comment by jh34ghu43gu** [comment]
> There isn't any reason to have any other checks, as this should catch everything.

You probably misunderstood jouva's first comment, I did too and had to reread it 3 times to get what he was mentioning (I even wrote out basically what you said).
If you use a script to spam this during a wave (after retrying) you will "play the drums". If you do this on last waves with thousands of dollars you can spam the buyback sound (which is incredibly loud relative to the rest of the game) for a good 15+ (usually 30+) seconds because the cost is only $5-$85. A cash check for less than $0 here doesn't help because it does cost money, but the game can't respawn you because you haven't selected a class yet. Both fixes are needed if we want to address both the money exploits and drum exploit..

**Comment by jouva** [comment]
Sorry if my original comment came off as confusing!

Yes, basically the point is that you can run this command before you pick a class as many times as you want. But if you do so while the game is mid-wave, you do not get the benefit of earning money, but you can still fill up the chat log and layer the playing of the buyback sound alert. So, if you only add the check against `iCost`, it'll prevent pre-wave spamming, but not mid-wave spamming. So while it would fix game breaking side of the exploit, it won't fix the griefing side of the exploit.

The player's current class being valid is another check that is necessary.

**Comment by kisak-valve** [comment]
Hello, per "Fixed exploit related to using the td_buyback command during Mann vs. Machine matches" in the [2023-03-01](https://www.teamfortress.com/post.php?id=190461) Team Fortress 2 update, please retest this issue.

**Comment by KalleKokosnott** [comment]
The issue is solved and it can no longer be reproduced with the steps provided. 
However, one may still use the command in question to spam the buyback audio cue (mvm_bought_in.wav), while simultaneously spamming the text chat, during an ongoing wave, though this will expend credits.

**Comment by jouva** [comment]
They did the negative check only, didn't they?

**Comment by EricS-Valve** [comment]
We didn't realize players were also doing this during an active wave, but we've added a check to prevent this behavior in the next update. We appreciate everyone who was posting the details here. Thanks.

**Comment by KalleKokosnott** [comment]
The "td_buyback" audio spam after a round has started, is no longer an issue after the 2023-03-20 update.
