### ISSUE TITLE
[TF2] Queue gets constantly cancelled without any player input

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#4950]
Sometimes, the game will start queueing and after a short while it will stop queueing. There is no notification or any indication why it stopped. I have no clue what causes this bug, however, restarting TF2 and/or Steam usually fixes the issue. 

If you are queued up with a party and one person is affected by this bug, it means the whole party can't queue. If said player leaves, the queues will work just fine.

This goes for both Casual and Mann vs. Machine, no idea about competitive.

**Comment by jh34ghu43gu** [comment]
Sometimes this is because your request to the GC is empty even if your client is showing maps selected. Deselecting everything then reselecting can sometimes fix it if this is the problem. This commonly occurs when people join/leave parties and/or the leader star is passed around. 

Other times it seems to relate to the GC thinking you are in a match you can't leave(?) Which can sometimes be fixed by restarting steam as you said. A lot of months ago this bug was especially egregious and was only fixed when the GC restarted on Tuesday, some of my friends had the bug persist for multiple days until the maintenance freed them; although I haven't heard of anyone running into such drastic effects in some time.

**Comment by Ashetf2** [comment]
There should be feedback in the form of a popup to the player when this occurs, mentioning the possible errors.

**Comment by Thespikedballofdoom** [comment]
Absolutely, I'm so sick of casting out the person who gets "infected" in the queue.

**Comment by AwesomeCoder412412** [comment]
Finally, a place to tell my story.

The year is 2021. I am just getting into TF2, having installed the game in January. I'm greatly enjoying my time with it, and on the fateful day of June 22nd, 2021, it started. Roughly 10 minutes before the tf2 update slated to release that day released, I attempted to queue up for causal with all maps selected. The queue popup was present for roughly 10 seconds before confusingly disappearing the same way it would if I cancel it manually. Confused, I re-queued and got into a match of 2fort after 2 seconds. Shrugging it off, mid-match I saw that there was an update available for tf2. Excitedly, I quit my game to install it. Little did I know what had just started. 

Before I tell the rest of my story about this infuriating glitch, allow me to recount what exactly happens when it occurs.

If an affected account tries to queue for casual, boot camp, mann up, competitive, or any combination of the four, the matchmaking will cancel in 3-20 seconds, varying randomly. It is still possible to get into matches with this glitch, you just have to find a match before the unknown countdown is up.

This glitch persisted on my account for at least 1.5 years, preventing me from enjoying TF2 to the fullest. I must have verified the game files and reinstalled tf2 and steam a million times over the course of that period. I removed all my configs, anything custom. I left and joined countless parties(a proposed solution online for this glitch). I scoured the internet for answers, only finding the occasional Reddit or steam community post all with the same answer: to verify my game files. It never worked. I even moved to a totally different computer, with no transfer of files between them. Nothing worked.

But do you want to know what the worst thing about this godforsaken glitch was? It was contagious.

Over the course of 1.5 years, I tried to introduce 2 of my friends to the game. When I queued up with them, of course, it didn't work. But when they left the party and restarted the game they had the glitch as well. The glitch has been persistent on their accounts for a very long time, and this has prevented them from getting into the game. They don't play anymore because of it, which saddens me. It's possible it still persists on their untouched accounts even today.

After 1.5 years, one day when I depressedly tried queuing for casual, the glitch didn't happen. I was elated. However, the next day it returned. From this point onward it would come and go, with the periods of its absence growing larger and larger. The last definitive date I can give for when it occurred was sometime during Scream Fortress 2022. I can only pray it stays away from my account, but it has a habit of popping up when you least expect it. I wish I learned of the TF2 bug tracker's existence much sooner, as for a large period of time I had an account that was consistently displaying this bug. On the off-chance that something's still there, I'll leave a link to my Steam profile. If my friends still have the glitch happening on their accounts as well I'll update this comment accordingly.

Please TF2 Team, look into this.

https://steamcommunity.com/id/theawesomecoder/

**Comment by felipsmartins** [comment]
not sure if my case is either related or not, but I can't queue for casual search.
Everytime the search stops after some seconds. :(

**Comment by Ruskki** [comment]
It's happening to me as well since a few days now. My friends can't queue with me because of it

**Comment by NULLYUKI** [comment]
Just noticed that this error probably is already being tracked in #2820 

So this issue is probably a duplicate and it would be better to move all the posted information here into #2820

**Comment by AwesomeCoder412412** [comment]
> Just noticed that this error probably is already being tracked in #2820 
> 
> 
> 
> So this issue is probably a duplicate and it would be better to move all the posted information here into #2820 

I'll provide further updates on #2820 then.

**Comment by NULLYUKI** [comment]
@kisak-valve Could check again, close this issue and transfer all the provided information into the already existing issue #2820

**Comment by kisak-valve** [comment]
Transferred to https://github.com/ValveSoftware/Source-1-Games/issues/2820#issuecomment-1787155567. Please continue discussing this issue on the older issue report.
