### ISSUE TITLE
[TF2, Hammer] func_rotating broken in TF2

### ISSUE THREAD

**Issue by nomer888** [ValveSoftware/Source-1-Games#517]
In Hammer for TF2, if one is to attach a brush to a func_rotating entity in a level, and attach an input, (a button for example, attack to use) and compile the map, open it in TF2, activate the button, the entity will not do anything.  No matter what setting or flag is edited/checked, it will not rotate.

It works in Counter-Strike:Source, which is the only other game I have tested it in.  I would expect to see the entity rotate upon the settings I chose, but instead, it does nothing once activated.  There are no specific settings to reproduce this, any setting does not change its functionality.

The Valve Developer Community Talk:Func rotating page will give even more specific details about this.

**Comment by Mecha-Weasel** [comment]
At first I thought, like I must have been doing something wrong.  But, func_rotating is such a simple entity (from a mapping POV), there isn't much to get wrong.

Wow, this seems like it would be something quick to fix.  Sad to see its been a known problem for literally "years".  :-(

**Comment by Mecha-Weasel** [comment]
PS: Might be nice for somebody with access to update the Func_Rotating documentation page (https://developer.valvesoftware.com/wiki/Func_rotating) to say this does not work with TF2.

**Comment by stevethepocket** [comment]
Done.

**Comment by kisak-valve** [comment]
From @V952 on #1265:

This is caused due to angle clamp. It happens when it's angles become unreasonable (k_flMaxEntityEulerAngle = 360.0 \* 1000.0f). Can be fixed by clamping angle between -180/+180 or 0/360.

```
if ( angles.x > 360.0f )    angles.x -= 360.0f;
if ( angles.x < 0.0f )      angles.x += 360.0f;
if ( angles.y > 360.0f )    angles.y -= 360.0f;
if ( angles.y < 0.0f )      angles.y += 360.0f;
if ( angles.z > 360.0f )    angles.z -= 360.0f;
if ( angles.z < 0.0f )      angles.z += 360.0f;
```

**Comment by worMatty** [comment]
Hi, there, kisak-valve.

Unfortunately func_rotating does not function properly in TF2 at all. If you stand on it, or stand on a func_brush that is parented to it, YOU will rotate, but both brush entities do not. They just stay still. I just tested it now using a newly-created entity with default values.

Thanks for picking up all of these issues. It's a nice surprise.

**Comment by kisak-valve** [comment]
Per "Fixed func_rotating entity not working properly in maps like 2Fort and Gravelpit" in the [2018-12-19](http://www.teamfortress.com/post.php?id=46984) TF2 update, please retest this issue.

**Comment by Technochips** [comment]
Just checked, and it now works, at least the clouds on 2fort.

**Comment by stevethepocket** [comment]
I was active in the TF2 mapping community for many years, and the lack of a working func_rotating function came up all the time, and not once do I recall hearing about Gravel Pit having any such entities. If anyone else has a clue what specifically the patch notes are referring to, I'm dying to know.

**Comment by agrastiOs** [comment]
@kisak-valve it is now fixed

**Comment by FlaminSarge** [comment]
@stevethepocket If there are clouds in the skybox then it might have been used for those.

@kisak-valve why was a secondary patch needed for cp_gullywash? Is this issue something that happens on a case-by-case basis for existing maps, and thus will all maps that use func_rotating need an update?

**Comment by stevethepocket** [comment]
@FlaminSarge According to the TF2Maps thread, the creator of Gullywash forgot to set the "Starts On" flag for those, and probably no one bothered to tell them because func_rotating being broken was a known issue. Also, it turns out Gravel Pit's rotating elements are a pair of radar dish thingies on the roofs. The more you know!

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.

**Comment by ENERGERMAN** [comment]
Hello, i don't know if i should make a new thread, but as it seems func_rotating was completly broken in Team Fortress 2. But in Counter-Strike: Source, it's also not completly working: After a certain number of rotations, the moving objects freeze and the server console will be spammed with errors. And through Google i know, that this bug also existed in Counter-Strike: Global Offensive, but this bug has been fixed in a [patch from 2017](https://blog.counter-strike.net/index.php/2017/03/18198/):
> – func_rotating objects no longer freeze and spam server console after rotating 1000 times


However in Counter-Strike: Source the bug still remains.

Here is a video and the description contains all useful information.:
https://youtu.be/Sa8A7HgrjFU

**Comment by kisak-valve** [comment]
Hello @ENERGERMAN, please open a new issue report.
