### ISSUE TITLE
[TF2] 32:9 Arch Linux Weird Screen Issue 

### ISSUE THREAD

**Issue by taulantxhakli** [ValveSoftware/Source-1-Games#5203]
I have been trying for days to figure out the issue behind this, but here I am.
To start, in case anyone would like to ask, here is my system's hardware:

    Distro:Arch Linux
    Kernel:6.5.3-arch1-1
    RAM:32 GB
    GPU Driver:NVIDIA 535.104.05
    GPU:NVIDIA GeForce RTX 3070 Ti
    CPU:AMD Ryzen 5 5600X 6-Core

When playing on Windows 11/10, I never had an issue with TF2, everything ran right out of the box. When I first installed Arch, it actually worked the first launch I had. For some reason, when I launched it again the next day, I got this weird graphical/resolution glitch that no one I have talked to seems to know how to fix: 
![GetImage](https://github.com/ValveSoftware/Source-1-Games/assets/58316986/5a186aa5-456d-4263-9625-abe02db2e277)

This has also happened in L4D2 and HL2. Though, when changing to Vulkan through the launch options, it runs normal and graphically better.

I reinstalled arch a second time to make sure it was not something I had done but still this issue persists. Am I just not understanding what happened or was there an update to Nvidia (or something pertaining to what the game uses) that would cause this?

Other games that I play, such as RDR2 or Quake II, all run fantastic on Arch, with all of the games set on Vulkan API.

Any help would be appreciated. I have a crippling addiction to TF2 (slightly jokingly, of course).

**Comment by taulantxhakli** [comment]
Just to add to this, I finally found someone else with the same issue that was not able to resolve this:
https://www.reddit.com/r/linux_gaming/comments/gpvsit/stretched_images_in_source_games_at_native/

As I said on Windows 10/11 everything worked fine, but Valve native games cause this really odd effect. Hope someone can point me in the right direction.

**Comment by taulantxhakli** [comment]
Another user I found on GitHub with the same issue:
https://github.com/ValveSoftware/csgo-osx-linux/issues/2429#issuecomment-767655160

**Comment by taulantxhakli** [comment]
Great news, I found the culprit to one of the issues, the second view on the top left. It was that dastardly HDR being enabled.
Here is an image with HDR on:
![hdr-on](https://github.com/ValveSoftware/Source-1-Games/assets/58316986/ed5d4c21-7a32-4566-b209-bf0af2a68c8e)


This is with HDR off:
![hdr-off](https://github.com/ValveSoftware/Source-1-Games/assets/58316986/a1e2ad81-f776-4fb2-a5eb-d8ada14e7044)

The issue that is still persisting in some servers, such as this one that runs 2Fort is the zoom in view. Also, for some strange reason, I cannot take a screenshot or look at the steam overlay or else it will cause the game to crash.

**Comment by Torston420** [comment]
Not sure why HDR is acting like that, but if the zoom only happens on some servers then my first guess is 'sv_restrict_aspect_ratio_fov'
Could you try setting it to 0 & 1 in a local game and report back?
You could also try using exclusive fullscreen and seeing if setting it to 2 behaves differently than 1.

**Comment by taulantxhakli** [comment]
> You could also try using exclusive fullscreen and seeing if setting it to 2 behaves differently than 1.

Just for the record, I mentioned that I cannot take screenshots using Steam because it crashes the game, which is why I have it in windowed mode so I can screenshot it. As for the `'sv_restrict_aspect_ratio_fov'`, I will try that and get back to you.

**Comment by taulantxhakli** [comment]
> Not sure why HDR is acting like that, but if the zoom only happens on some servers then my first guess is 'sv_restrict_aspect_ratio_fov' Could you try setting it to 0 & 1 in a local game and report back? 

Changing between 0 & 1 does nothing in a local game.

**Comment by meltwaterpulse1b** [comment]
The same thing happens to me. I wrote on the steam discussions page but I guess its abandoned.
I just took the maps out of my queue and leave when I get put into the maps.
Linux mint, samsung g9 ultrawide 32:9

Do you also get this bug?
https://steamcommunity.com/app/440/discussions/0/3768987637135757603/

**Comment by taulantxhakli** [comment]
> Do you also get this bug? https://steamcommunity.com/app/440/discussions/0/3768987637135757603/

Yeah that happens to me sometimes when I play on regular Casual servers too. Though that is a TF2 issue primarily, as I had that on Windows 10/11 as well.

**Comment by taulantxhakli** [comment]
Was pondering whether to put this here or not, but could this be the issue?:
```c
[taulant@adminman ~]$ xrandr
Screen 0: minimum 8 x 8, current 5120 x 1440, maximum 32767 x 32767
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected primary 5120x1440+0+0 (normal left inverted right x axis y axis) 1mm x 1mm
   3840x1080    119.97 + 239.97    59.97  
   5120x1440    239.76*  120.00    59.98  
   2560x1440    239.90   120.00    59.95  
   2560x1080    119.88    60.00    59.94  
   1920x1080    119.88    60.00    59.94  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
```
Would it be possible to either remove the `3840x1080` or make the `5120x1440` preferred?

**Comment by taulantxhakli** [comment]
Update:
When making my monitor 3840x1080 then launching TF2, it changes the monitor back to 5120x1440 but the game actually is still set to 3840x1080 in-game, but stretched to 5120x1440. If that makes sense.

This is what it looks like when doing that:
![2023-09-27_22-09](https://github.com/ValveSoftware/Source-1-Games/assets/58316986/3c5f363d-3175-44f2-8b57-0a5442736816)

So I finally cracked the nut. Now, I need to figure out why the xrandr is using both resolutions and how to delete the 1080 one.

**Comment by darksabrefr** [comment]
I get the ultrawide fov problem too and I have a different configuration. I'm under Ubuntu 23.10 and have an Asus RoG 32:9 screen in 5120x1440 resolution, coupled with a GeForce RTX 4070 Ti graphic card (with nvidia proprietary drivers v545).
The fov problem only occurs in precise maps, like Banana Bay or 2Fort, and never on some others, like Gold Rush or Badwater Basin. Some maps may partially present the problem if they have multiple zones, Hightower version Halloween event for example: the first part of the map is running fine, but the second one, in Hell shows the bug.
But even for maps where 32:9 is usable, the render is over-pixelized compared to other Source games, even more since the `-vulkan` switch is available for most of them, except TF2. I simply think the linux native version of the game cannot handle correctly these high resolutions and the fact that we can launch the game at these ones in fullscreen only, is a clue. In fact, when I see the behavior of the game in fullscreen mode, I think it cannot renders images at an higher horizontal resolution of 1920 pixels, and is stuck to the native vertical resolution (1440 for me) because this is the precise resolution that the game sets when I select the 1920x1080 (my screen can handle 16:9 ratio too, it's my personal workaround to play on incompatible maps): 1920x1440, a 4:3 resolution that nobody ever used ! And as a consequence, the image in slightly stretched (a 4:3 image rendered with by screen in 16:9).

For the small duplicated image in the the top left corner bug, I fixed it like other people: by disabling HDR. The same bug (but with a different visual) in presents in Portal 2 or L4D2 a can be fixed by lowering some visual options in game (I suppose that at some point it disables HDR effects, but that's not explicit in these games) or by using the `-vulkan` switch (the better option).

It's very sad that the Valve "flagship" Linux game that should be TF2, is, in fact, the less compatible with Linux systems. It's even more frustrating when you know that the Windows version used through Proton doesn't present these problems... but cannot be used to play online !

**Comment by darksabrefr** [comment]
I have more data about these bugs (pixelization one, HDR one and fov one, the last in fact, is a render issue, not a fov problem. And I have graphical other bugs that I've not mentioned above), they are related to a probably hard limit of width of 4096 pixels in the steam linux runtime, the thing that runs Source games in Linux, in OpenGL mode. I can't test above 1440 pixels for height, but I suppose them same limitation exists.
Starting the game with these params, and all pre-cited bugs will be vanished: `-w 4096 -h 1440 -window -noborder`
To see all these bugs in action, simply set a value greater than 4096, like `-w 4097 -h 1440 -window -noborder`
I hope this is sufficiently precise to get at least a response from the Valve team!

**Comment by taulantxhakli** [comment]
Issue resolved as of the latest TF2 update (x64 bit and -vulkan launch option).
It runs exactly as intended and even better performance. My dreams have finally been realized.
