### ISSUE TITLE
[TF2] Extendfreeze needs to return to deal with cheaters

### ISSUE THREAD

**Issue by Nitroxyz** [ValveSoftware/Source-1-Games#5353]
The only people using the extendfreeze command are those who look to check if a teammate is cheating. The bug which allows you to see the enmy team is nearly unusable anyways. The major issue is in the fact that other than, extendfreeze, there is no reliable way to tell if a player is hacking

**Comment by JoriKos** [comment]
I think a better solution to this would be to add a console command to set the time it takes for you to go to spectator after killing yourself. Currently, it takes quite a bit, but with this console command (maybe something like tf_time_spectate_after_suicide) it could be decreased to 0 so that dying would immediately transfer you to spectate to someone.

This could be combined with another feature that add a "Spectate" button to the scoreboard (when the option to use the mouse on the scoreboard is turned on) when clicking on someone's name. This would allow for somewhat optimal spectating of people without having to add the ability to spectate through the spectator team.

**Comment by kisak-valve** [comment]
Hello @Nitroxyz, this issue is already being tracked at #5275.

Closing as a duplicate.
