### ISSUE TITLE
[TF2] Linux x64 beta fails to launch.

### ISSUE THREAD

**Issue by Twig6943** [ValveSoftware/Source-1-Games#5468]
![steamlog](https://github.com/ValveSoftware/Source-1-Games/assets/119701717/000a01d5-079e-4496-b73e-7d57c9e37fdc)
![image](https://github.com/ValveSoftware/Source-1-Games/assets/119701717/326683cf-dfb2-458e-a9ab-19404d3a551a)
[bugreportvideo](https://github.com/ValveSoftware/Source-1-Games/assets/119701717/1ca03773-891b-466d-a2c2-b8564796089c)

One thing worth mentioning is that I have a modified version of the /home/$USER/.steam/steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point because if I don't windows games such as Brawlhalla fail to launch. Also the current version of TF2 launches fine regardless of my v2entrypoint file as its a native game. 

V2EntryPointIssue.mp4
https://github.com/ValveSoftware/Source-1-Games/assets/119701717/db704baa-9261-475b-818c-bed8a075d288

**Comment by kisak-valve** [comment]
Hello @Twig6943, the beta branch is intended to be run inside of the Steam Linux Runtime 3.0 (Sniper) container environment. Your choice to hijack the setup of that container environment is not supportable.

The issue you're seeing with the runtime environment is due to https://github.com/ValveSoftware/steam-runtime/issues/420 and the NVIDIA 390 series video driver being the last driver series to support your Fermi generation video card.

**Comment by Twig6943** [comment]
Does this basically mean theres no way of me playing tf2 when this beta rolls out?

**Comment by Joshua-Ashton** [comment]
The GL mode will be kept for compatibility with older hardware but will mostly unsupported. You can use -gl.

**Comment by OfficialPixelBrush** [comment]
Can confirm it's also borked on Steam Deck, and I've changed nothing. I've reinstalled it multiple times too. Dunno how to force it to use the Steam Linux Runtime 3, as I'd wager that it'd just use it without further adjusting.

**Comment by Joshua-Ashton** [comment]
This is known, and will be fixed at least when it moves out of Beta.
