### ISSUE TITLE
[TF2] There is a new crash related to objectors.

### ISSUE THREAD

**Issue by sarahkittyy** [ValveSoftware/Source-1-Games#5603]
I think if you create a big conscientious objector sign it crashes everyone online. I've had people crashing my servers constantly because I had a guy take credit for doing it going "oops :) all I have to do is press 3 :)".

The specific crash is
![image](https://github.com/ValveSoftware/Source-1-Games/assets/31551546/ee48cf37-36b7-4388-b3a9-cd58e39f6f49)

I've found people talking about this here:
https://steamcommunity.com/app/440/discussions/0/6733519291684766045/
https://www.unknowncheats.me/forum/team-fortress-2-a/631959-crash-exploit-info-stay.html
https://www.reddit.com/r/tf2/comments/1c1ttrc/new_instant_crashing_cheat/

Please help this is serious and probably very easy to do

**Comment by sarahkittyy** [comment]
Looked up the backpack.tf of the user claiming credit for crashing everyone and found this exploitative decal.
![image](https://github.com/ValveSoftware/Source-1-Games/assets/31551546/e3aea0fa-c8cf-46ad-b513-505e5eded4ef)

**Comment by sarahkittyy** [comment]
I believe it is also maybe related to the newly discovered way to add gifs / apngs as decals since they are hosted on steam
https://www.reddit.com/r/tf2/comments/1bxxb9a/so_i_guess_there_is_now_a_way_to_add_working_gifs/

**Comment by Platina6978** [comment]
I'm not sure if it's a rule but I don't think we should put links from cheating forums here.
Either way thanks for bringing this to light, hope this gets fixed ASAP!

**Comment by sarahkittyy** [comment]
https://www.reddit.com/r/tf2/comments/1c308ab/crashing_my_game_with_a_conscientious_objector_he/

Another post on social media about this issue.

**Comment by JoriKos** [comment]
> I'm not sure if it's a rule but I don't think we should put links from cheating forums here. Either way thanks for bringing this to light, hope this gets fixed ASAP!

Seems like it provides some context as to why it happens, unlike the other posts, so it's actually a useful link.

**Comment by NooctisUGC** [comment]
Does anyone have a simple fix to stop these?

**Comment by sarahkittyy** [comment]
Set up tf/item_whitelist.txt to ban the Objector until a fix is found.

**Comment by TrenchcoatCraig** [comment]
Has anyone figured out how players are doing this in the first place?

**Comment by Nocrex** [comment]
For people looking for a fix for casual this guide should do it:
https://steamcommunity.com/sharedfiles/filedetails/?id=3049594375

**Comment by gabrielwoj** [comment]
> For people looking for a fix for casual this guide should do it: https://steamcommunity.com/sharedfiles/filedetails/?id=3049594375

Hello, I'm the creator of that guide. I wrote it after I researched what server the decals were being downloaded from, once decals were loaded on TF2. With that, I already knew about the functionality of "hosts", so I made the guide as it can be immensely helpful for many people.

I appreciate you linking here. I was going to yesterday but I was having trouble logging to GitHub.

One thing I'd like to note, however, is that the hosts method is the only "fix" for this bug, even on Community Servers without sv_pure restrictions. Note that mods that remove decal functionality aren't really removing the decals from being downloaded, only getting rid of the material proxy called "CustomSteamImageOnModel", which is used for items that have decalability.

On these mods, due to the lack of the proxy, the decals won't show up in-game VISUALLY, however, they are still downloaded by the game. That means even if you can't see them, the crashing exploit will most likely still happen as the game have downloaded the problematic decal and it leaks to the memory.

With the hosts method, however, it won't be able to communicate with the server that stores the decals, pretty much making the exploit not work. If it can't communicate with the server, then it can't download it, therefore, it's the only protection against this exploit in the meantime until it gets fixed by Valve themselves.

**Comment by johnathon-walnut** [comment]
> Has anyone figured out how players are doing this in the first place?

Replacing the PNG data when it's uploaded, see CApplyCustomTextureJob

**Comment by KaelaSavia** [comment]
Until TF2 Team rolls out fix, here is plugin for SourceMod server operators to disable all item decals from being rendered on server.

Requirements: TF2 Items extension
```
#include <sourcemod>
#include <tf2items>

bool bReceivedNotify[MAXPLAYERS + 1] =  { false, ... };

public void OnClientPostAdminCheck(int iClient) {
	bReceivedNotify[iClient] = false;
}

public Action TF2Items_OnGiveNamedItem(int iClient, char[] sClassName, int iItemDefinitionIndex, Handle &hItem) {
	if(iItemDefinitionIndex == 474 || iItemDefinitionIndex == 619 || iItemDefinitionIndex == 623 || iItemDefinitionIndex == 624) {
		static Handle hItemHandleCopy = INVALID_HANDLE;

		if (hItemHandleCopy != INVALID_HANDLE) {
			CloseHandle(hItemHandleCopy);
			hItemHandleCopy = INVALID_HANDLE;
		}

		hItem = TF2Items_CreateItem(OVERRIDE_ALL);		
		TF2Items_SetClassname(hItem, sClassName)
		TF2Items_SetItemIndex(hItem, iItemDefinitionIndex);
		TF2Items_SetNumAttributes(hItem, 2)
		TF2Items_SetAttribute(hItem, 0, 227, view_as<float>(548814534));
		TF2Items_SetAttribute(hItem, 0, 152, view_as<float>(1656248994));
		
		
		TF2Items_SetFlags(hItem, OVERRIDE_ATTRIBUTES);
		hItemHandleCopy = hItem;
		
		if(!bReceivedNotify[iClient]) {
			bReceivedNotify[iClient] = true;
			RequestFrame(Notify_ItemChange, EntIndexToEntRef(iClient));
		}
		return Plugin_Changed;

	}
	return Plugin_Continue;
}

public void Notify_ItemChange(any ref) {
	int iClient = EntRefToEntIndex(ref);
	if(iClient == INVALID_ENT_REFERENCE)
		return;
		
	PrintToChat(iClient, "Decal items such as The Conscientious Objector are temporarily disabled due to crash exploit!");
}
```

**Comment by Kacey2k** [comment]
**Piggybacking off this issue**, some people were circulating a video from a scammer that showcased them launching programs using a supposed payload within their objector image, effectively appearing as a method of RCE.

Upon inspection of the objector used in the video, there was no payload, or really any data that made it stand out from any normal objector. 

The creator of the hoax is likely attempting to exit scam collectors of odd items such as that, using the video to make them appear authentic.

**Comment by angelfor3v3r** [comment]
Just to save people the trouble from going to that awful cheating site, here are some details about the crash that I've found. Here's hoping for a fix.

The reason for the crash is due to PNG decoding. Once your client requests the item's picture from the steam cloud/remote storage, it tries to decode an abnormally large PNG file and causes `malloc` to fill up a lot of the 32-bit address space of TF2. On Windows, the executable is marked as `/LARGEADDRESSAWARE` so it has 4GB of virtual memory to use.

First off, your client eventually calls into `SCustomImageCacheEntry::PollDownload` inside `game\client\econ\tool_items\custom_texture_cache.cpp`. Inside here is a call to `ISteamRemoteStorage::GetUGCDetails` which passes a `UGCHandle_t` and checks the size of the file. If the file is above around `69630` (or in the SDK, defined as `k_nMaxCustomImageFileSize`) bytes then it skips the download. 

It seems like some of the images causing crashes are around `60840` bytes, and have a size of `5000x100000`, which passes the previous check. Then we land inside `ImgUtl_LoadPNGBitmapFromBuffer`, which calls `ImgUtl_ReadPNGAsRGBAFromBuffer` (both of which are inside `common\imageutils.cpp`).

The crash happens because of these lines:
```
row_pointers = (png_bytepp)malloc( height*sizeof(png_bytep) );
pResultData = (unsigned char *)malloc( rowbytes*height );
```
...Which can sometimes calculate PNG sizes that are up to `2000000000` bytes big, if someone is using a malicious PNG. This is a very easy fix.

If you want to test the crash for yourself, you can call the function `int GetCustomTextureGuiHandle( uint64 hCloudId )` and pass a malicious cloud ID (they're 64-bit unsigned integers for me). With a debugger attached, you'll notice the allocation failing here.

Here's hoping for a fix soon.

**Comment by bakugo** [comment]
@gabrielwoj 

> On these mods, due to the lack of the proxy, the decals won't show up in-game VISUALLY, however, they are still downloaded by the game. That means even if you can't see them, the crashing exploit will most likely still happen as the game have downloaded the problematic decal and it leaks to the memory.

As far as I can tell from analyzing the code, the decal download is triggered by the proxy itself. Meaning if the proxy is not present on the item's material, decals will not be downloaded.

**Comment by 43ongah9aihtdgoihdsgh32089oeh** [comment]
related to 64bit, u cannot apply the decal unless u have enough virtual memory

**Comment by johnathon-walnut** [comment]
> related to 64bit, u cannot apply the decal unless u have enough virtual memory

This is not true, you can do apply this on 32-bit.

**Comment by gabrielwoj** [comment]
> @gabrielwoj
> 
> > On these mods, due to the lack of the proxy, the decals won't show up in-game VISUALLY, however, they are still downloaded by the game. That means even if you can't see them, the crashing exploit will most likely still happen as the game have downloaded the problematic decal and it leaks to the memory.
> 
> As far as I can tell from analyzing the code, the decal download is triggered by the proxy itself. Meaning if the proxy is not present on the item's material, decals will not be downloaded.

Hmm, but disabling the Proxy still shows up your decals on the inventory screen, backpack, and I'm mostly sure while inspecting other players too. So even if that was the case, if you inspected someone having this "zipbomb" decal, it still could crash I'd assume.

**Comment by angelfor3v3r** [comment]
> > > related to 64bit, u cannot apply the decal unless u have enough virtual memory
> > 
> > 
> > This is not true, you can apply this on 32-bit.
> 
> does this exploit require modifying actual game functions? or is it the image itself

I don't have an item to test but from what I've seen they're just 5000x100000 blank PNG files, that fit right under the 60k byte limit. If that can't be uploaded, then I don't know. It would be easy to inject it by modifying game functions, though.

**Comment by johnathon-walnut** [comment]
> > > related to 64bit, u cannot apply the decal unless u have enough virtual memory
> > 
> > 
> > This is not true, you can apply this on 32-bit.
> 
> does this exploit require modifying actual game functions? or is it the image itself

To get past the game resizing whatever you upload to 128x128, and to avoid the actual malloc calls from making the preview images, yes you need to modify the actual game functions. The image itself is what causes the crash though, see the post above that goes through ImgUtl_LoadPNGBitmapFromBuffer

**Comment by Joshua-Ashton** [comment]
This will be fixed in the next release.

**Comment by TrenchcoatCraig** [comment]
What will happen to the existing glitched items, and the players who created them?

**Comment by sarahkittyy** [comment]
If I had to guess I'd imagine you could still keep them and maybe even make them they just wouldn't render in-game or crash anyone anymore.

**Comment by Joshua-Ashton** [comment]
The items will simply show a missing texture.

**Comment by sarahkittyy** [comment]
yaay it's fixed nya

**Comment by Joshua-Ashton** [comment]
nya indeed
