### ISSUE TITLE
Time between quacks of the duck journal has lengthened by several times

### ISSUE THREAD

**Issue by Pheophex** [ValveSoftware/Source-1-Games#5685]
The Duck journal quacks when used in game and it was usually quiet and frequent use but now it seems to span between 30ish seconds to a minute between use

**Comment by jh34ghu43gu** [comment]
This is because some of the sounds cannot be loaded

MP3 initialized with no sound cache, this may cause janking. [ ambient_mp3\bumper_car_quack5.mp3 ]
*** Invalid sample rate (0) for sound ')ambient_mp3\bumper_car_quack5.mp3'.
MP3 initialized with no sound cache, this may cause janking. [ ambient_mp3\bumper_car_quack1.mp3 ]
*** Invalid sample rate (0) for sound ')ambient_mp3\bumper_car_quack1.mp3'.

**Comment by Jeffonehundred** [comment]
Just letting you all know, I am having this issue too. Something to take note of, when you die, you can press the action key, doing so causes the duck sound to play.

**Comment by Pheophex** [comment]
> Just letting you all know, I am having this issue too. Something to take note of, when you die, you can press the action key, doing so causes the duck sound to play.

If i recall this has been a thing since the journals release with the end of the line update, it was also audible to the people you spectated as well

**Comment by Pheophex** [comment]
didnt mean to close it sorry

**Comment by BapplesB** [comment]
So, did anyone figure out the solution to this? For me, it also mutes other sounds after some time playing (hitsound, killsound, taunt sounds, getting resuply, spy declocking, demoman charges etc.)

**Comment by Jeffonehundred** [comment]
@BapplesB I do not think so, I think someone programmed it on purpose to reduce fun :(

**Comment by jh34ghu43gu** [comment]
Update while trying to make a vpk to fix it:
Quack 1 2 3 5 11 appear to be the broken ones and 4 and 9 appear to be working. They all have the same sample rate according to the analyzer I used but they do have different bit rates. I re-encoded all of the problem ones with a slightly lower bitrate and they all worked (I think) in a vpk so maybe these just need re-encoded and are missing some headers? I'm too lazy to go further since I have something that works. Here's a gamebanana link for anyone who wants: https://gamebanana.com/sounds/74669

**Comment by Jeffonehundred** [comment]
@jh34ghu43gu What encoder did you use Lame/mp3?

**Comment by jh34ghu43gu** [comment]
> @jh34ghu43gu What encoder did you use Lame/mp3?

Yes

**Comment by jh34ghu43gu** [comment]
This was fixed today with the shorter mp3 patch note change.

**Comment by espimarisa** [comment]
Confirmed as working in today's patch. :)

**Comment by Jeffonehundred** [comment]
YAY! Now I get to use my duck jurnel! (Have not tested myself)

**Comment by Pheophex** [comment]
Can confirm its working now!

**Comment by Pheophex** [comment]
I accidentally closed it again! but the issue is resolved anyway! 😂
