### ISSUE TITLE
Windows 7 -vulkan does not work.

### ISSUE THREAD

**Issue by Jeffonehundred** [ValveSoftware/Source-1-Games#5782]
Vulkan does not work at all. Attempt to start the game with "-vulkan" causes nothing to happen. Steam shows the green play button, then shows the blue cancel button, then the blue stop button. Then it just shows the green play button. There is no message, no warring, or any indication at all that the game started.

**Comment by Jeffonehundred** [comment]
I have tested Vulkan working on a Gtx 1070 gpu. I used this program "https://github.com/skeeto/vulkan-test" along with other games that run Vulkan natively.

**Comment by ChampionCynthia** [comment]
TF2 uses DXVK 2.x for Vulkan, which requires Vulkan **1.3**.

The latest driver for the NVIDIA GTX 1070 on Windows 7 is version 474.89, which doesn't support Vulkan 1.3.

To use Vulkan, you'll need to upgrade to Windows 10/11 or switch to Linux.

**Comment by Jeffonehundred** [comment]
> DXVK
Oh, so its just using that emulator? I thought it was native Vulkan support. Why is your reply not mentined anywhere? Not even the Tf2 wiki? Someone should mention that the Vulkan stratup command only uses Dxvk, and does not use Vulkan natively.

**Comment by kisak-valve** [comment]
Hello @Jeffonehundred, @ChampionCynthia assessment is accurate. This driver series does not provide Vulkan 1.3 which is required for the DXVK translation layer to work.

Closing as a system / video driver issue. (Vulkan 1.2.174 https://vulkan.gpuinfo.org/displayreport.php?id=26697)

**Comment by metapea** [comment]
> Hello @Jeffonehundred, @ChampionCynthia assessment is accurate. This driver series does not provide Vulkan 1.3 which is required for the DXVK translation layer to work.
> 
> Closing as a system / video driver issue. (Vulkan 1.2.174 https://vulkan.gpuinfo.org/displayreport.php?id=26697)

Will you update the requirements for tf2 or add [VulkanRT](hhttps://vulkan.lunarg.com/sdk/home). Since Vulkan 1.3 can be install in windows 7 with VulkanRT with a supported GPU like [GTX 1070](https://vulkan.gpuinfo.org/displayreport.php?id=29911).

**Comment by kisak-valve** [comment]
Hello @metapea, you've linked a Windows 10 driver install which is a year and a half newer than the 474.xx legacy video driver branch which is available for Windows 7. This does not make a compelling argument.

**Comment by metapea** [comment]
> Hello @metapea, you've linked a Windows 10 driver install which is a year and a half newer than the 474.xx legacy video driver release series which is available for Windows 7. This does not make a compelling argument.

The reason why i added that [display report](https://vulkan.gpuinfo.org/displayreport.php?id=26697) was because it was frame of reference (pre [ChampionCynthia](https://github.com/ChampionCynthia) comment) for installing Vulkan 1.3, because for some GPUs like a [GTX 650](https://vulkan.gpuinfo.org/listreports.php?devicename=NVIDIA+GeForce+GTX+650) can only go up to Vulkan 1.2 even with an OS like windows 11.

**Comment by Jeffonehundred** [comment]
> good work around
I do not think this. I would rather have the game work nativity, rather then using an v ulkanemualtor, emulating a direct x environment.

**Comment by metapea** [comment]
> > good work around
> 
> I do not think this. I would rather have the game work nativity, rather then using an vulkan emulator, emulating a direct x environment.

I'm i was talking about just directly installing VulkanRT being a work around. Not the redirect part if that's what you're referring to. I didn't say anything about emulation.

**Comment by ChampionCynthia** [comment]
Before further confusion,

@Jeffonehundred's reference to "emulation" is about the DXVK translation layer. TF2's Vulkan implementation is actually done using DXVK which translates the game's original DirectX calls to Vulkan. It is actually "translation" rather than "emulation". The game doesn't have an actual Vulkan renderer like the OP would prefer.

@metapea talks about the actual system that runs Vulkan by mentioning the use of VulkanRT as a workaround for the NVIDIA drivers on Windows 7 not meeting the minimum requirements of DXVK. However, this is not possible.

**Comment by MasterSlenderTR** [comment]
I found a workaround for forcing -vulkan on Windows 7.

1) Download last version of DXVK compatible with Win7 https://github.com/doitsujin/dxvk/releases/tag/v1.10.3
2) Drag d3d9.dll from dxvk archive into \steamapps\common\Team Fortress 2\tf
![1](https://github.com/ValveSoftware/Source-1-Games/assets/50411937/ca569634-0b17-4a6b-897c-35c4d00fcdb7)
3) Rename original dxvk_d3d9.dll to dxvk_d3d9.dll.old (or delete it)
4) Rename d3d9.dll to dxvk_d3d9.dll
![2](https://github.com/ValveSoftware/Source-1-Games/assets/50411937/18923042-857e-4124-ba3d-a9d2779a55e7)
5) Launch the game with "-vulkan"
![3](https://github.com/ValveSoftware/Source-1-Games/assets/50411937/c28b2395-6df7-4bfe-acea-2d4ad2e1be0b)
6) Profit.
![Capture](https://github.com/ValveSoftware/Source-1-Games/assets/50411937/0dc9fdf1-9834-4226-96b4-f9e340d4d5f6)
![Capturee](https://github.com/ValveSoftware/Source-1-Games/assets/50411937/7aa08b28-5a2a-4441-a9d2-0251728eebeb)

Note: For this method to work, you need to be using 32-bit executable of Team Fortress 2. The easiest way to do that is you delete new tf_win64.exe, rename old tf.exe to tf_win64.exe, then launch the game using steam.

**Comment by Jeffonehundred** [comment]
Progress was made here for getting the vulken work.
https://github.com/ValveSoftware/Source-1-Games/issues/5662#issuecomment-2067804252
https://github.com/ValveSoftware/Source-1-Games/issues/5662#issuecomment-2067776584
 But its not as complete as @MasterSlenderTR has does here.

**Comment by metapea** [comment]
> Note: For this method to work, you need to be using 32-bit executable of Team Fortress 2. The easiest way to do that is you delete new tf_win64.exe, rename old tf.exe to tf_win64.exe, then launch the game using steam.
Nice, also thanks for the tip with tf_win64.exe. Again, There no command to launch the 32-bit far as i know.
I had that in my mind since does [dxvk/releases/tag/v1.10.3](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3) works on some windows 10 games, only been reminded a while ago that dxvk is being used and didn't take in that tf2 is using 100% dxvk and you can just replace the .ddl for some reason.

**Comment by Jeffonehundred** [comment]
> There's no command to launch the 32-bit far as i know.

Right as you had just helped me, @instafixer just made a command "https://github.com/ValveSoftware/Source-1-Games/issues/5674#issuecomment-2067798708" you should check it out, it launches the 32 bit vision without the usual bugs. Thank you for the fix with vulkan , i'll try this out just to make sure in case something happens later on.
