### ISSUE TITLE
[TF2] [Linux] Can't set speaker configuration to Headphones even after the update

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/Source-1-Games#5882]
> Fixed an issue selecting surround sound audio settings (Headphones, 4, 5.1, 7.1, etc.) 

When I set speaker configuration to Headphones via the game's menu, it resets to 2 Speakers when I close the menu.

**Comment by NULLYUKI** [comment]
Probably related to https://github.com/ValveSoftware/Source-1-Games/issues/5618 ?

**Comment by kisak-valve** [comment]
#4867 is a better match.

**Comment by NULLYUKI** [comment]
> #4867 is a better match.

I don't think this is a better match, because in that issue, the user cannot select any other audio option besides `2 speakers` 
https://github.com/ValveSoftware/Source-1-Games/issues/5618#issuecomment-2071135058 while here it was mentioned that the user can change the audio option, but it would just reset back to the previous audio option.
