### ISSUE TITLE
[TF2] Contracker Not Counting Points

### ISSUE THREAD

**Issue by Desksmash** [ValveSoftware/Source-1-Games#5974]
My Contracker has been working up until lately when it just stopped counting the contract points I was getting. I would complete a contract and it would say I got the points but wouldn't add to my Contracker. I'm just confused why it would do this and would like to know how to fix.

**Comment by JoriKos** [comment]
Please don't intentionally make duplicate reports.

You reported the same issue at #5944, closed it, and reopened it now. Please reopen the original issue instead.

**Comment by punchy499** [comment]
Not sure if this is the same issue, but my points are not being tracked properly as I've completed every contract and sub-objective related to each one yet still remain on the "silver" level of Contracker with 6490 contract points instead of the needed 6840 for australium. You and one other person on the steam forums are the only people I've seen talking about this so I want to add my say into it.

Also not sure why the people here seem to feel that telling you not to post something is more helpful than providing any form of input related to the issue at hand.
