### ISSUE TITLE
 [TF2] [Linux x64] Game crashing xwayland in gnome

### ISSUE THREAD

**Issue by AlexeySFr** [ValveSoftware/Source-1-Games#6037]
How to reproduce
If you enter review mode in gnome during the game, and switch between virtual desktops or move the game to another desktop, the game crashes, killing server x11 and applications that run on it, including steam
OpenGL version TF2 works fine
Kde have mostly same problem but not like in gnome

1. Linux distro : Arch linux  Linux 6.9.3-zen1-1-zen
2. Desktop Gnome 46.2 (Wayland)
3. GPU: Nvidia RTX 4060Ti  with nvidia driver beta  555.42.02

**Comment by TheBoctor** [comment]
If you look at your output from `journalctl --user` (or the GNOME Logs GUI) when this happens, is there mention of "drm_syncobj" or similar?

I've been noticing this, too, since explicit sync support landed in GNOME 46.1, and it may be related. Plasma does not exhibit the issue, as explicit sync was not merged for 6.0.x (but was for 6.1, at the time of writing!)
I am using a Radeon 6700XT, so this issue does not seem Nvidia-specific. I am on Arch as well, but using the normal kernel (likely unrelated.)

**Editing, to avoid unnecessary bumping/mess on the issue:** I have done some unscientific tests under Gamescope, GNOME 46.2, and Plasma 6.0.5 with the explicit sync patches. In all cases, TF2 (native and in Proton) can crash when manipulating the window in certain ways, while just playing normally, or while quitting. However, when I entirely disable the Steam overlay, I can play TF2 and other Source mods, native or otherwise, to my heart's content with no crashing.

You may get different results on Nvidia, but I have a hunch that the in-game Steam overlay is somehow violating the protocol for explicit sync, causing the offending processes (Steam/steamwebhelper) to be killed. This is similar to a newly revealed Firefox bug.

**Comment by AlexeySFr** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/6037#issuecomment-2147704860

Hello TheBoctor, thanks for advice
I found something related on “drm_syncobj” in my journal
```
wp_linux_drm_syncobj_surface_v1#279: error 4: No Acquire point provided
WL: error in client communication (pid 1266)
Window manager warning: Treating resize request of legacy application 0x3c00002 as a fullscreen request
```
Also, disabling steam overlay doesn't help me, game still crashing xwayland

**Comment by AlexeySFr** [comment]
Also, this issue open in xorg issue tracker on gitlab
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1688

**Comment by AlexeySFr** [comment]
Closing this issue due to a fix on the xwayalnd side 
See https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1571

**Comment by TheBoctor** [comment]
I patched XWayland with the diff from that MR, but this issue still occasionally happens. Not sure if you've yet tried doing the same.

Edit to avoid bumping/spamming: I found your Arch forum post, it looks like you were using a different branch of xorg-xwayland and a different PKGBUILD, where I was trying to apply the patch to the current one. I'll try again with the branch you used.

**Comment by AlexeySFr** [comment]
> I patched XWayland with the diff from that MR, but this issue still occasionally happens. Not sure if you've yet tried doing the same.

Well I don't have issue right now with his mr


Are you sure you built xwayaland with the modifications you need?

anywayIf you have done it right,please provide information by following the link about this problem on giltab xorg
