### ISSUE TITLE
Alleged Distribution of links boasting Child Sexual Abuse material by Bots in Team Fortress 2 casual lobbies

### ISSUE THREAD

**Issue by Fizintine4ever** [ValveSoftware/Source-1-Games#6063]
As the title says There's been 3 separate incidents of _alleged_ distribution of what is advertised as links containing Child sexual abuse material.

I came across the 1st incident on on X(twitter)  being [this](https://x.com/che3semaker/status/1798391368207012123) which appears to be a player spamming CSA links in the lobby chat box.

The 2nd such incident which was also reported on X being [this](https://x.com/Dorflat/status/1798677943473803336) which appears to be a cosmetic item with a questionable name that indicated a CSA link was the description of the said item , the link appears to be a .onion link.

3rd incident was posted on r/tf2's subreddit being [this](https://www.reddit.com/r/tf2/comments/1dbde74/alert_bots_are_now_impersonating_uncle_dane_while/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) on which a individual appears to be impersonating Uncle Dane , the famous tf2 youtuber , where the individual yet again is posting alleged CSA links in lobby's chat box , same as the 1st incident

Why has valve failed to act on these very serious allegations? 

If this happens to be Valve's first acknowledgement of this issue then how quickly can we receive a a official statement from Valve authenticating this crime and when will the community be informed if these were troll users playing a sick joke or if it  actually was bots advertising CSA links. 

Update 1 :- There's been one more instance of the said CSA link spam (That I'm aware of and is backed by photographic evidence) which appears to be another Bot advertising CSA material by spamming messages in lobby's chat box , A discord user posted this image 
![bot2](https://github.com/ValveSoftware/Source-1-Games/assets/172162077/e0ed410d-fa71-4f3e-890f-fba63c7ad784)

 in a server I was in , the following has been translated by the said user as ''I sell CP in private (number) contact first via steam // 10 GB = 2 keys'' .

This issue is only on it's way to get more attention if Valve doesn't put a stop to it ASAP. 

The fact that problems like these which have very harsh real world implications are left unresolved and aren't official acknowledged is outright shameful for a corporation like Valve.  

Update 2 :- Up to this point , all of these incidents have a few select players behind them , big bot hosters like Rosnehook are completely against pedos , there's been people in the tf2 community calling out bot hosters (who they think are behind all the instances of CP spam) , but Rosnehook deny these accusations and are against the said individuals , their bots or the server is in no way associated with supplying CSAM , and supposedly all the spam texts advertising Rosnehook discord server with selling CSAM are people trying to defame them.

**Comment by wgetJane** [comment]
i think this repo is for tracking bugs and feature requests for the Source engine, not for feeding attention to malicious bot hosters

discussion regarding this is already supposed to be contained within #3477

**Comment by Fizintine4ever** [comment]
@wgetJane I suppose your argument about the bot discussion being contained strictly within #3477 does make a point , I guess I will copy paste what I wrote and add it as a comment , thank you for pointing my possible mistake out.

**Comment by KaelaSavia** [comment]
> i think this repo is for tracking bugs and feature requests for the Source engine, not for feeding attention to malicious bot hosters
> 
> discussion regarding this is already supposed to be contained within #3477

This post is valid concern and issue to be reported related to TF2's casual servers which are ran by Valve. 

It's seperate matter from bots problem, as players/automated accounts are distributing CSAM material which is something that needs to be immediately taken action upon, such as filtering links from casual's in-game chat messages.

Whether it's bots/automated accounts or actual players who are doing this is seperate matter entirely although still connected to bot problem in TF2

**Comment by Fizintine4ever** [comment]
@KaelaSavia thank you very much for agreeing with my take here , this issue surpasses the age old problem of "cheaters in a video game" as now It's players committing illegal activities , I've seen about a dozen  accounts of this happening through fellow players but I only posses some what convincing photographic evidence of 4 such instances (I made a update on a rather more recent one) , it's a shame valve has not taken any actions yet and possibly the first few instances of these problems have been apparently going on for 2 weeks at this point.

**Comment by pay2lose2** [comment]
Hey, just to let you know, the person that's most likely apart of this is none other than [ArenaTeamPlayer](https://steamcommunity.com/profiles/76561198868164015) (obsessed with konata), one instance showed him using "Uncle Dane". Another which has been shown in rosnehook server (that's where link redirects) showing him using "Big Joey" username. Also keep in mind that **Rosnehook doesn't accept pedophiles and will never be associated with them, ATP is most likely targetting the server and we have yet to know why**. Also to keep in mind, **ROSNEHOOK IS NOT A CSEM SHARING SERVER, WON'T BE AND NEVER WILL**

Also for god sake, do not look up his backpack.tf

![ATP](https://github.com/ValveSoftware/Source-1-Games/assets/121765166/11cd209d-b156-4f97-807a-bdfb7d1b66b8)
![ATP's Persona History](https://github.com/ValveSoftware/Source-1-Games/assets/121765166/30c3273c-6c5a-4b8b-898b-d7430d8409a1)
![ATP's profile 08/06/24](https://github.com/ValveSoftware/Source-1-Games/assets/121765166/e018a17b-8584-4f89-a1d2-93e22478fa71)

Another player that might be responsible is [Auditor](https://steamcommunity.com/profiles/76561198167566727) and his friends (unknown and might not be confirmed, tho the account spamming the messages is [Sniper](https://steamcommunity.com/profiles/76561199645297492), which he has in friends)

![image](https://github.com/ValveSoftware/Source-1-Games/assets/121765166/e6706117-6462-4fc7-972c-4b2fc5f5008f)

While yes, I agree that something should've been done, I don't agree with the fact people are immediately pointing it to bot hosters instead of investigating further (ATP never hosted but got impersonated, I am not sure what about Auditor)

**Comment by Fizintine4ever** [comment]
@pay2lose2  I appreciate you for looking in on the matter and bringing a few of these culprits to light , I myself found out more about Arena Team Player but didn't think about updating any more info , I also agree with your take on me using bot hosters , I don't think I  should use the word bot  hosters to call out what's allegedly a few individuals , I've been to rosnehook Discord server and they're completely against the pedos and advertisement of CSAM in away what so ever , either directly associating their DC server with CSAM or their bots advertising malicious links , so I'll make those tweaks right away

And I gotta agree it's high time for Valve do something over very illegal activities persisting in their game cause reporting players does absolutely nothing anymore in Tf2.

**Comment by pay2lose2** [comment]
@Fizintine4ever I apperciate you not immediately sending 15 death threats saying how bad I am for speaking up about it

**Comment by RandomTNT** [comment]
This is not made by bot hosters, the CSAM is being sent by arenateamplayer, and his fellow pedophilic friends, and apperantly, AuditorMadness.

**Comment by RandomTNT** [comment]
^^ never mind i am blind.
Rosnehook has nothing to do with arenateampedo

**Comment by RandomTNT** [comment]
> Also for god sake, do not look up his backpack.tf

- I regret what i have seen
- I hope he will share a cell with Lugenbeal

**Comment by wgetJane** [comment]
i guess this place is just steam discussions 2 now

**Comment by mastercoms** [comment]
This issue is infested with cheaters throughout, it's just some way to get attention or spread misinformation. I would advise closing it

**Comment by UndefinedBHVR** [comment]
@kisak-valve This issue is related to the bot crisis, and should likely be closed as duplicate for #3477.

As for the player and bots in question, I would recommend reporting their accounts on Steam, and making a report to the authorities as well. Posting this issue on Github isn't as helpful as making an actual report, especially if you can provide evidence of their actions. Valve actively reads steam reports.
