### ISSUE TITLE
[TF2] Tiny Timber can be painted, but no paint can will change its appearance

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#6078]
The Tiny Timber cosmetic is set as paintable in `items_game.txt`, yet the textures are not set up so paint will actually work. This could potentially waste paint cans people have bought, it should be a simple fix by removing
```
"capabilities"
{
	"paintable"		"1"
}
```

from the `items_game.txt` entry (number `30321` and line `76533`)

**Comment by jh34ghu43gu** [comment]
This can be fixed by replacing `xms2013_pyro_wood.vmt` with the `xms2013_pyro_wood_1.vmt` in `materials\models\workshop\player\items\pyro\xms2013_pyro_wood\` of the tf2_misc_dir.vpk

https://imgur.com/uT46oKX
[vpk that fixes it if added to custom folder](https://github.com/user-attachments/files/15838531/tinytimberfix.zip)

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed a problem with the Tiny Timber not displaying paint after being painted

This needs to be retested.

**Comment by tmob03** [comment]
It's fixed (painted top, unpainted bottom) @kisak-valve 
![image](https://github.com/user-attachments/assets/2c3a1ea7-e875-4525-b12a-ed30986c39c3)
![image](https://github.com/user-attachments/assets/e6f22d3f-ae89-40b6-b23a-8240ceedb5e7)

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
