### ISSUE TITLE
[TF2] Audio crackling with ALSA

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#65]
Issue transferred from ValveSoftware/steam-for-linux#554
@bucaneer posted at 2013-01-05T23:02:16Z:

This may not strictly be a bug since I understand PulseAudio is the officially supported backend, but in case there are any plans to support bare ALSA, there is an issue to report. Starting the game with ALSA (by setting environmental variable <code>SDL_AUDIODRIVER=alsa</code>), all sounds crackle and, when there multiple simultaneous sources of sound, cause game stuttering. This line appears in the terminal output repeatedly:

<code>ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred</code>

The issue appears to be related to buffer size / sampling rate since setting different values of those in ~/.asoundrc changes the amount of crackling (although I couldn't manage to find a combination that would eliminate it completely).

Also, the game does not recognize my speaker setup - I use 5.1 surround speakers, but the game only offers the option of 2 speakers in the audio options tab.

OS: Arch Linux, kernel 3.3.7-1-ck
Soundcard: Creative Audigy LS (driver module: <code>snd-ca0106</code>)

**Comment by Rabcor** [comment]
Actually, I had this same issue with in-home streaming. I traced it to my speaker settings, I set the client speaker option to 5.1 output and got this insane crackling sound. When I set it back to stereo all went to normal.

My host PC only has a stereo (through HDMI) speaker setup, which might have been related. But I also have a rather elaborate .asoundrc config file.

The parts that should be applicable here are these:

`pcm.dmixed {
	type asym
	playback.pcm {
		# See plugin:dmix at http://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html
		type dmix

		# Don't block other users, e.g. the Timidity midi-player daemon
		# http://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html
		ipc_key_add_uid true

		ipc_key 5678293
		ipc_perm 0660
		ipc_gid audio

		slave {

			channels 6
		
			pcm {
				#format S16_LE
				#format S24_LE
				format S32_LE
				#format FLOAT_LE

				#rate 44100
				#rate 48000
				rate 96000

				# http://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html
				# Maybe helps
				nonblock true

				type hw
				card 0
				device 0
				subdevice 0
			}

			# period_size 512 with buffer_size 16384 stops crackling in xmame
			# 320 breaks flash - https://bbs.archlinux.org/viewtopic.php?id=129458
			#period_size 512
			period_size 1024

			# If too large, use CONFIG_SND_HDA_PREALLOC_SIZE=2048
			buffer_size 16384
		}
	}
	capture.pcm "hw:0,1"
	#slave.pcm "hw:Loopback,0,0"
}

pcm.!surround51 {
	type plug
	slave.pcm "dmixed"
}`

But for good measure [here is the whole thing](http://pastebin.com/rxJujxVs).

There are about three reasons I can think of for this error, at least in my context with in-home streaming, that is that some bug occurs when the host PC's speaker setup has fewer channels than the Client PC; or that the steam linux client isn't properly configuring itself to use the "surround51"pcm when set to 5.1 mode, or lastly in case there is some abstraction layer that was meant to set the host's game configuration to a 5.1 speaker configuration and then forward that to the client if the client is configured for a 5.1 speaker setup, then there is a bug somewhere in that code. Since I don't know the inner workings of the in-home streaming I can't really pinpoint it.

Either way ironically my contribution might rather belong in the original placement of this thread in the steam-for-linux git rather than source engine, unless the source engine is somehow used for in-home streaming.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
