### ISSUE TITLE
[HL2 EP2] No video on panel

### ISSUE THREAD

**Issue by SobGAV** [ValveSoftware/Source-1-Games#6819]
No video image on the panel
Нет видеоизображения на панели
![20241127210019_1](https://github.com/user-attachments/assets/42b230f0-240d-4102-8ac6-905615a8de97)

**Comment by Gulliblepikmin** [comment]
I'm pretty sure that's intentional given how:
1. It's always been like that. (really old footage as proof: https://youtu.be/pB07wQLPaXo?t=413)
2. The device's texture is reminiscent of that of speaker, like a radio or walkie talkie as examples.
3. That texture had to be specifically added there by a developer. The texture used for the device's speaker(?) isn't a part of the main texture used for the device, and the similar devices in Black Mesa East's airlocks have their own screen texture, which is visible while they're not in-use (and again isn't the main texture used for the device).

**Comment by SobGAV** [comment]
Thanks!
