### ISSUE TITLE
[HL2] Crane music missing

### ISSUE THREAD

**Issue by SobGAV** [ValveSoftware/Source-1-Games#6821]
The door goes through the roof
![20241130080044_1](https://github.com/user-attachments/assets/c46a4aa0-bfab-420b-a266-1d1ef8f5be96)

**Comment by SobGAV** [comment]
![20241130080044_1](https://github.com/user-attachments/assets/37c3f26f-b670-4e15-a683-e8fc3778a18c)

**Comment by megakarlach** [comment]
Music on this map works fine for me through, just the volume itself is low and that was it.

**Comment by marigi64** [comment]
This is because the music triggers only when the player touches the ladder to the crane by walking into it. If they press use on the crane to get in instead, the music won't play. 

This can be fixed by removing the output for the ladder:
"OnPlayerGotOnLadder" "crane_music,PlaySound,,0,1"

and adding this output to the crane entity:
"PlayerOn" "crane_music,PlaySound,,0,1"

**Comment by SobGAV** [comment]
> Это потому, что музыка запускается только тогда, когда игрок касается лестницы крана, заходя в него. Если вместо этого он нажмет «использовать» на кране, чтобы войти, музыка не будет воспроизводиться.
> 
> Это можно исправить, удалив вывод для лестницы: "OnPlayerGotOnLadder" "crane_music,PlaySound,,0,1"
> 
> и добавляем этот вывод к сущности крана: "PlayerOn" "crane_music,PlaySound,,0,1"

I never paid attention before. Thank you!
