### ISSUE TITLE
[TF2] The new map Overcast contains stolen assets and copyright infringement

### ISSUE THREAD

**Issue by IronFoxGaming** [ValveSoftware/Source-1-Games#6859]
The map Overcast, added in today's update, contains a laundry list of textures and props made by other members in the TF2 community without any credit or profits going to their creators. The map also features some textures generated by AI, as well as a TV prop full on playing a clip from the movie The Thing, which is copyright infringement on top of everything else. This is in direct violation of section 6D of the Steam Subscriber Agreement, specifically the part about what you submit having to be something you created and have legal ownership of. 

I believe a full list of the stolen workshop assets has already been compiled and sent to Eric by the TF2Maps community, so I won't go into detail about those, but I'll show the movie clip as can be found in the map, since I feel that's the most damning part of the SSA violation. It plays on a TV in RED spawn, next to a framed image of TheReportOfTheWeek with an oil paint AI filter over it. The clip itself is the texture materials/models/props_arctic/television/snapshots.vtf. I was unable to get it to display on my end, as it appears to be triggered by something, or activated at random, so the first image here comes from @DidTF2GetUpdate on Twitter.

![image](https://github.com/user-attachments/assets/80929077-88ff-45a7-99d8-f453718258ed)
![image](https://github.com/user-attachments/assets/9b575750-54fe-4f69-8ed5-18cfed0b7248)
![image](https://github.com/user-attachments/assets/fe135e93-e0a4-4dc0-9c1a-ac33d26024d2)

**Comment by ghost** [comment]
Gonna be honest there, map deserve to either be removed or something else. Cause ai stuff and thieft is bad.

**Comment by programmedsun** [comment]
> Gonna be honest there, map deserve to either be removed or something else. Cause ai stuff and thieft is bad.

It seems like the copyrighted material is from another pack the map creator used. I have no problem using AI, and the map creator has already credited the pack creators.

**Comment by DiskIntegrity** [comment]
> It seems like the copyrighted material is from another pack the map creator used. I have no problem using AI, and the map creator has already credited the pack creators.

Just because the pack creators are "credited" in a singular texture does not mean its okay for the map creators to profit off others work. When making a map _**all**_ creators must have a share of the profit _(IE be a contributor in revenue split list)_ unless they themselves choose not to. Some of these creators weren't even credited in the first place and had no idea their stuff was in the map to begin with. Yes, their assets are "free to the public" but are not meant to be taken and used for official map releases like this.

**Comment by programmedsun** [comment]
> Just because the pack creators are "credited" in a singular texture does not mean its okay for the map creators to profit off others work. When making a map all creators must have a share of the profit (IE be a contributor in revenue split list) unless they themselves choose not to. Some of these creators weren't even credited in the first place and had no idea their stuff was in the map to begin with. Yes, their assets are "free to the public" but are not meant to be taken and used for official map releases like this.

It's never okay that a map creator profits from others' creations but what singular texture? It's in the workshop description. The map creators explained in the comments that it was an accident because they were new to the map scene. There is something wrong when the asset creators don't know if their asset is in a video game.

The entire drama is all about being hostile over a human fault, and to be honest, it's good to know that mapmakers are basically non-human beings (robots even?), and they don't tolerate any human faults. (_btw, I believe the correct way would have been to notify the map creator at the workshop comments, telling them that assets are being used that aren't being credited instead of throwing a tantrum over GitHub and on the map's comments page_)

**Comment by Ashetf2** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/6859#issuecomment-2544198073

dude stealing content is against the law, even if you didn't know
