### ISSUE TITLE
[TF2]Beggar's Bazooka incorrectly applying "reload time increased hidden" attribute?

### ISSUE THREAD

**Issue by CrimsonTautology** [ValveSoftware/Source-1-Games#877]
According to the [item schema](http://git.optf2.com/schema-tracking/tree/Team%20Fortress%202%20Schema?h=teamfortress2#n23624) the Beggar's Bazooka is suppose to have a hidden increased reload time attribute, 30% more so then the stock Rocket Launcher.  However testing this in game it appears that the reverse is actually true; you can load and fire a rocket faster then you can with a normal rocket launcher that has no rockets loaded.

[I've attached a demo file demonstrating this.](https://www.dropbox.com/s/h81pks373g5s2hj/bazooka.dem)

**Comment by Wasmanr2** [comment]
Since Beggar's Bazooka have a higher attack intervall it will look like that the reload is faster.
But its not.
Because the Rocket launcher have an attack intervall of 0.8 sec and 0.92 reload time.
And the Bazooka have 0.24 attack intervall, reload time however is 1.192 sec

@kisak-valve  you may close this

**Comment by kisak-valve** [comment]
Closing per the last comment.
