### ISSUE TITLE
No music plays in any valve game

### ISSUE THREAD

**Issue by recursor94** [ValveSoftware/Source-1-Games#884]
Even though every other sound in the game is working, for some reason none of the music in any valve source game is playing even though the music is set to maximum volume. This problem is occurring in every game in the orange box and in half life 1. 

I am only having this problem on linux--the problem does not exist on my windows installation of steam and the orange box.

This is the output of the developer console during one instance when music should have been triggered in half life 2:

`Failed to load sound "*music/HL2_song10.mp3", file probably missing from disk/repository` 

I noticed similar errors for other sound files but every other sound seems to be playing correctly, though a related observation is that none of the nihilanth recordings are playing in half life 1.

I have verified the local game cache, steam reports a successful verification. Are the music files really missing, or is the problem in game? If the problem is on my end, how can I fix it?

Thanks for your help,
recursor

**Comment by their** [comment]
We have noticed this issue on two Fedora boxes since about January, 2015. In the console the error shows many instances of failed to load various MP3 sounds. E.g.: "Failed to load sound "vo/soldier_PainSevere03.mp3", file probably missing from disk/repository". Also 

Setting SELINUX to permissive mode allows the sounds to work properly.

Does anyone have ideas for a workaround without setting SELINUX to permissive?
