### ISSUE TITLE
Run key doesn't work in HL2

### ISSUE THREAD

**Issue by sean-bennett112** [ValveSoftware/Source-1-Games#895]
No matter what I map the run key to, whether on keyboard or controller, I always end up walking.

Macbook Air
OS X 10.7.5
Intel Core i5

Edit: Also why can I not seem to add any labels to this issue?

**Comment by kisak-valve** [comment]
Hello @sean-bennett112, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by PietJanHein** [comment]
Unfortunately this problem is NOT solved. I started to play the game again in the last days. To be exact: Half-Life 2: Update, but that shouldn't matter. I noticed that frequently all of the sudden the sprint-button quits working withotu any clear reason! Sometimes twice within 1 minute. All that I can do to fix it is closing the game and restarting it. Note that reloading a saved file does not work, only closing the game and starting it again fixes it. I verified that my powermeter is not empty but whatever I do, until I shut down the game and start it again, Gordon refuses to sprint, this long after he wears the nano-suit, like at the end of the Ravenholm map.
